backend/src/worker.rs

smol issue where a deno script with parameters named `main` or `run`
will try to assign over imported main or the run function.
This uses the spread syntax to unpack the arguments and arrange them in
an array in argument order.  Instead of making assignments to the scope.
(I am not very JavaScript expert so I'm trying to be careful but I _think_ this is a fine way to do this.)

deno script args spread to array

---

backend/src/worker.rs

Returning an array from a deno script fails the job because it can't serialize into a `Map<String, Value>`.
In JavaScript `typeof []` is `'object'`.
Wasn't 100% sure what the correct behaviour is -- for Python scripts, tuples are handled differently from lists.  So I guessed and did the thing that it does for lists.

wrap array results from deno scripts in object

---

backend/Cargo.lock
backend/Cargo.toml
backend/src/jobs.rs
backend/src/lib.rs
backend/src/main.rs
backend/src/scripts.rs
backend/src/worker.rs
backend/src/worker_flow.rs

hosts on :8001
This probably isn't entirely right but I'm hoping it's in the ballpark.
I'm re-reading issue #289 for the seventh time I'm only now realizing what you wanted out the the gauge. I used a histogram instead because it has a timer and also I don't know what I'm doing.
I guess the gauge seems a little awkward if it's not updated before being queried. Like if a worker is waiting for a job it won't show up in the metrics unless it's continually updating the gauge? I'm not sure. You can take this over if it's clear to you otherwise I'll try to clean it up based on any feedback.

fix: prometheus histogram for worker job timer

---

frontend/src/lib/components/Editor.svelte
frontend/src/lib/components/InputTransformForm.svelte

Only the last instance of Monaco editors catches the custom commands mapped on key bindings
https://github.com/microsoft/monaco-editor/issues/2947

Fix Editor formating when saving while using dynamic inputs.

---

.github/workflows/backend-test.yml
.github/workflows/docker-image.yml
backend/src/fixtures/base.sql
backend/src/flows.rs
backend/src/worker.rs

Worker modifed to drop the `broadcast::Sender` after subscribing a
`broadcast::Receiver` to it.  If the last Sender is closed, the
Recievers are closed.  But this will never happen unless run_worker
drops the Sender passed to it.
Tests don't go through the web/http stuff so they skip serialization and
all that. Not sure if this is good or bad, maybe we want both.
each test marked with `#[sqlx::test]` is run in a new database named
_sqlx_test_N. There's quite a bit of overhead to this compared to
running tests in transactions but it provides more isolation and the
implmentation is a bit simpler.
backend/src/fixtures/base.sql is run by `#[sqlx::test]` to set up some
data when testing.  It also adds a trigger used to synchronize a bit,
it's kind of a hack.  Ideally the testing database …

 backend tests for python job and deno flow

---

backend/src/lib.rs
backend/src/main.rs
backend/src/worker.rs

I think this was just added a couple months ago.  If all Senders drop
the Receivers close.  This change helps avoid creating Senders that you
never send on that are just held in scope and prevent the channel from
closing.

pass broadcast::Receiver instead of Sender

---

backend/src/lib.rs
backend/src/main.rs
backend/src/tracing_init.rs
backend/src/worker.rs

also remove tiny bit of raceyness from worker tests, there's a bit of
sync around Once but it's short so it should be fine

make initialize_tracing sync and infallable

---

backend/src/parser_ts.rs

Adding support for `x: typ | undefined` and `x: typ | null` to the typescript parser

feat(parser): support union type with null | undefined

---

frontend/src/lib/script_helpers.ts

* Fix typo: ros -> rows
* Use `const` instead of `let` for variables that are never reassigned.
* Replace 1 tab with 4 spaces for consistency.

Changes to the Deno trigger script template

---

backend/src/worker.rs
frontend/src/lib/components/FlowBuilder.svelte
frontend/src/lib/components/FlowPreview.svelte
frontend/src/lib/components/FlowPreviewContent.svelte
frontend/src/lib/components/FlowStatusViewer.svelte
frontend/src/lib/components/ModuleStep.svelte
frontend/src/lib/components/flows/FlowBox.svelte
frontend/src/lib/components/flows/FlowTimeline.svelte
frontend/src/lib/components/flows/flowState.ts
frontend/src/lib/components/flows/flowStateUtils.ts
frontend/src/lib/components/flows/utils.ts
frontend/src/lib/stores.ts
frontend/src/lib/utils.ts
frontend/src/routes/run/[...run].svelte

Refactor how the previews are used to populate the prop picker and add code completion in the raw JS editor.
Each module contains its latest result.
When a preview  is run:
- `mapJobResultsToFlowState` takes the results of a preview. and updates the FlowState accordingly.
- Each `ModuleStep` uses `getStepPropPicker` to get the pickable properties and its corresponding type definition
This implementation doesn't support intermediate results in for loops yet.

feat(frontend): Fix flow preview

---

backend/src/flows.rs
backend/src/parser_ts.rs
backend/src/worker.rs
backend/src/worker_flow.rs

- renames FlowModule.input_transform to input_transforms
- parse_deno_signature prints source on failure instead of debug
representation of AST

run failure_module

---

nsjail/download.config.proto
nsjail/run.deno.config.proto
nsjail/run.python3.config.proto

contents of /etc/ssl symlink to /etc/pki on my system (Fedora) so some
programs (like pip) fail without /etc/pki

optional ro mount /etc/pki in nsjail

---

backend/src/jobs.rs
frontend/src/routes/scripts/get/[...hash].svelte

It was possible to run them using a webhook, but not through an endpoint. This PR aims to fix that so the user can target a specific version of the script to run.

feat(job): run job by hash

---

backend/src/lib.rs

This is a little bit annoying. You seemed amicable to having this removed on the call but if you are concerned about initiating a lot of database connections at once let me know.
It's particularly annoying because the delay between workers increases with the number of workers.

remove delay between spawning each worker

---

backend/src/worker.rs

There were a couple issues with the current implementation:
1. When reading stdout and stderr from the child, as soon as we hit EOF on one we would stop reading from both (line 1420). This could lead to the return value not being read from the job program.
2. Lines read from stdout and stderr are put into a channel and read elsewhere with `rx.recv()` (line 1497) but that channel isn't read until empty.  It is only read in the `while !done.load(...)` (line 1449) loop and that loop can stop after any `.store(true, ...)`. Which happens when the child exits, when the job is cancelled, when either stdout or stderr reach EOF...
This can be verified by putting `dbg!(rx.recv().await)` or a similar assertion after the while loop before returning from that function. It shows the channel still …

reorganize handle_child

---

frontend/src/lib/components/LogViewer.svelte

"are" because "logs" is plural

No logs is available -> No logs are available

---

frontend/src/lib/components/ModulePreview.svelte
frontend/src/lib/components/script_editor/LogPanel.svelte

"Test to see result here" is missing an article for "result".

see result -> see the result

---

frontend/src/lib/script_helpers.ts

* `await`s `wmill.getInternalState()` because we need to.
* `await`s `wmill.setInternalState(newState)` because it returns a Promise and we probably want to catch errors while setting the state.
* replaces a tab intend because the remaining lines use four spaces.

wmill.getInternalState() needs to be awaited

---

frontend/src/lib/components/TestJobLoader.svelte

commit 9592c92f70ce9b94e141031c663ccb0cf01ef7d7 introduced a fix for an issue described in #649. After mentioned fix frontend performs 2 requests instead of 1.
This fix can be considered as a vol.2 for #649

fix(frontend): do only one request if job is completed [related to #649]

---

backend/src/parser_go.rs
backend/src/worker.rs
frontend/src/lib/components/DisplayResult.svelte
frontend/src/lib/components/ScriptEditor.svelte
nsjail/run.go.config.proto

Fix #697 
Some limitations, it doesn't work with named structs, only inlined structs and `json:'XX'` must always be specified as a tag

feat: support struct in Go as script parameters

---

python-client/wmill/pyproject.toml
python-client/wmill_pg/pyproject.toml

this is related to https://github.com/windmill-labs/windmill/issues/736#issuecomment-1279679730
turns out that `wmill` and `wmill_pg` require python3.10 now
```console
docker run -it python:3.9 /bin/bash
```
```console
pip install wmill && python3 -c 'import wmill'
pip install wmill_pg && python3 -c 'import wmill_pg'
```
vs
```console
docker run -it python:3.10 /bin/bash
```
```console
pip install wmill && python3 -c 'import wmill'
pip install wmill_pg && python3 -c 'import wmill_pg'
```

chore(python-client): update minimal python version

---

frontend/src/lib/components/scriptEditor/LogPanel.svelte

Updated an element that was unnecessarily an `h2`.

fix(frontend): Fix text styling in script creator

---

backend/.cargo/config.toml

Actually enables the existing configuration and adds --no-rosegment.

Cargo config improvements

---

deno-client/mod.ts

related to 10e1de84760b6b7eec92397117c44a938b0bc358

fix(deno-client): add missing approver encoding to hmac api request

---

backend/oauth_connect.json

usecase:
> as a windmill user I want to provide email of user to which slack direct message should be send
rationale:
https://api.slack.com/methods/users.lookupByEmail needs to be used. it requires `users:read.email` (which needs to be acquired together with
`users:read` - more info: https://api.slack.com/scopes/users:read.email)

feat(backend): extend default scope set for slack resource

---

backend/windmill-api/src/static_assets.rs

rationale for setting `'unsafe-inline'` is that it cannot be more void than the lack of `script-src` but it still might add some benefits

fix(backend): improve csp

---

backend/windmill-api/src/lib.rs
backend/windmill-api/src/static_assets.rs

bug description:
```
Refused to load the script 'https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993' because it violates the following Content Security Policy directive
```
it was decided to define CSP as an environment variable

chore(backend): set csp based on env var

---

frontend/src/routes/resources.svelte
frontend/src/routes/variables.svelte

background:
I was confused while reading
> The OAuth token is kept up-to-date in the background by Windmill using its refresh token
next to
> The access_token is expired, it will get renewed the next time this variable is fetched or you can request is to be refreshed in the dropdown on the right.
for me this descriptions are mutually exclusive. `kept up-to-date in the background` sounds like there is some background scheduled job that refreshes the token even if it's not used

chore(frontend): (opinionated) description improvement

---

deno-client/mysql.ts
deno-client/pg.ts

I'm using https://deno.land/x/mysql2@v1.0.6/mod.ts only because https://deno.land/x/mysql@v2.11.0/mod.ts has bug that I described in https://github.com/denodrivers/mysql/issues/128#issuecomment-1331477637
hopefully this bug will be fixed soon, then I guess we can switch from https://github.com/sail-sail/mysql2 to https://github.com/denodrivers/mysql
tested locally with:
```ts
import { mysqlClient, mySql } from "./mysql.ts";
const db = {
host: '0.0.0.0',
port: 3306,
user: 'root',
password: 'change-me',
database: 'test',
};
const conn = await mysqlClient(db);
await conn.execute('CREATE TABLE IF NOT EXISTS pets (name varchar(255), kind varchar(255))');
await conn.execute('INSERT INTO pets VALUES (?, ?)', ['behemot','cat']);
const [r] = await conn.execute('SELECT * from pets');
conn.end(); …
```

feat(deno-client): support mysql

---

cli/main.ts
cli/workspace.ts

I decided to change this and use `--create` on the existing `workspace add` command. I think this is much more natural to use then the previous `workspace create ...` + more flexible to ensure state is as expected.

feat(cli): Allow workspace to be newly created

---

frontend/src/lib/components/Dropdown.svelte
frontend/src/lib/components/Popover.svelte
frontend/src/lib/components/Tooltip.svelte
frontend/src/lib/components/common/table/AppRow.svelte
frontend/src/lib/components/common/table/FlowRow.svelte
frontend/src/lib/components/common/table/ScriptRow.svelte

- tooltip got smaller and cursor no longer indicates that it's clickable
- dropdown icon is vertical and narrower

feat(frontend): Update tooltip and home list dropdown

---

frontend/src/lib/components/common/button/Button.svelte
frontend/tailwind.config.cjs

Added new `frost` color the palette (inspired by [Nord](https://www.nordtheme.com/)) because setting a 90% background opacity is not always an option

feat(frontend): Add frost to color palette

---

frontend/src/lib/components/apps/components/table/AppTable.svelte
frontend/src/lib/components/apps/components/table/AppTableFooter.svelte

Table header and footer are now always visible, scrolling happens only on the table body

feat(frontend): Update app table component styles

---

.github/workflows/docker-image-arm.yml

This should fix the error seen here trying to push the image, https://github.com/windmill-labs/windmill/actions/runs/3924415790/jobs/6708660689.

Add `packages: write` for ghcr push

---

.github/workflows/uffizzi-build.yml
.github/workflows/uffizzi-preview.yml

I could not comment on locked PR #1106 so I've opened this new PR to get Uffizzi previews working better.
The most important change here is using Uffizzi' reusable workflow at our `v2` branch. This will keep you up to date with the latest changes. I suspect this version mismatch with our API is causing the failures such as this https://github.com/windmill-labs/windmill/actions/runs/3933057820/jobs/6726352392#step:16:25
Some other minor improvements are included: error handling, quote handling, formatting, etc.

Use Uffizzi workflow `v2` and other minor improvements.

---

frontend/src/lib/components/Popover.model.ts
frontend/src/lib/components/Popover.svelte
frontend/src/lib/components/Tooltip.svelte
frontend/src/lib/components/apps/editor/AppPreview.svelte
frontend/src/lib/components/apps/editor/TablePanel.svelte
frontend/src/lib/components/apps/editor/settingsPanel/InputsSpecsEditor.svelte
frontend/src/lib/components/common/button/Button.svelte

- the app builder header row is now fixed to the top in preview mode as well
- fixed styling issues
- handled error when the inputs of the button component are tied to free user input (table column selection)

fix(frontend): Show app builder header always on top

---

frontend/src/lib/components/sidebar/WorkspaceMenu.svelte

With the side menu collapsed, it wasn't clear which workspace was selected

fix(frontend): Add highlight to selected workspace

---

.github/uffizzi/docker-compose.uffizzi.yml
.github/workflows/uffizzi-build.yml
.github/workflows/uffizzi-preview.yml

We wanted to enable the GitHub login button for windmill previews. Windmill has a few configuration features that made this easier than other applications, including the easy OAuth configuration and ability to specify the `BASE_URL` path. I got this working in about a day.
You can see this running here https://pr-4-deployment-12160-windmill.app.uffizzi.com/
For this PR changeset, you'll want to specify a GitHub Actions Secret with Name `OAUTH_JSON_BASE64` and whose value is a base64-encoded `oauth.json` file with configuration for a GitHub OAuth App. Here's mine as an example:
```json
{
"github": {
"id": "afe59a7afe911b5b0714",
"secret": "[redacted]"
}
}
```
This secret will be read by the `uffizzi-preview` workflow and injected into the compose file before Uffizzi deploys it. That …

Enable GitHub OAuth for Uffizzi Previews.

---

frontend/src/lib/components/TestJobLoader.svelte
frontend/src/lib/components/apps/components/DisplayComponent.svelte
frontend/src/lib/components/apps/components/dataDisplay/AppBarChart.svelte
frontend/src/lib/components/apps/components/dataDisplay/AppHtml.svelte
frontend/src/lib/components/apps/components/dataDisplay/AppPieChart.svelte
frontend/src/lib/components/apps/components/dataDisplay/AppScatterChart.svelte
frontend/src/lib/components/apps/components/dataDisplay/AppText.svelte
frontend/src/lib/components/apps/components/dataDisplay/AppTimeseries.svelte
frontend/src/lib/components/apps/components/dataDisplay/PlotlyHtml.svelte
frontend/src/lib/components/apps/components/dataDisplay/VegaLiteHtml.svelte
frontend/src/lib/components/apps/components/helpers/RunnableComponent.svelte
frontend/src/lib/components/apps/components/helpers/RunnableWrapper.svelte
frontend/src/lib/components/apps/components/table/AppTable.svelte
frontend/src/lib/components/apps/editor/ComponentEditor.svelte
frontend/src/lib/components/apps/editorUtils.ts
frontend/src/lib/components/apps/utils.ts

Loading is displayed only on initialization (subsequent computes don't hide the component behind the loading layer) and recompute is unavailable during this time

feat(frontend): App initial loading animations

---

frontend/src/lib/components/DisplayResult.svelte

Support filename
`return {"file": base64_str, "filename": "icons.zip"}`

feat(frontend): Minimal support for custom filenames

---

frontend/src/lib/components/apps/components/display/AppIcon.svelte
frontend/src/lib/components/apps/components/display/AppImage.svelte
frontend/src/lib/components/apps/components/helpers/AlignWrapper.svelte
frontend/src/lib/components/apps/components/inputs/AppDateInput.svelte
frontend/src/lib/components/apps/components/inputs/AppFileInput.svelte
frontend/src/lib/components/apps/components/inputs/AppNumberInput.svelte
frontend/src/lib/components/apps/components/inputs/AppRangeInput.svelte
frontend/src/lib/components/apps/components/inputs/AppSliderInputs.svelte
frontend/src/lib/components/apps/components/inputs/AppTextInput.svelte
frontend/src/lib/components/apps/components/inputs/currency/AppCurrencyInput.svelte
frontend/src/lib/components/apps/components/inputs/currency/CurrencyInput.svelte
frontend/src/lib/components/apps/components/layout/AppDivider.svelte
frontend/src/lib/components/apps/components/layout/AppTabs.svelte
frontend/src/lib/components/apps/editor/component/Component.svelte
frontend/src/lib/components/apps/editor/component/components.ts
frontend/src/lib/components/apps/editor/componentsPanel/CssSettings.svelte
frontend/src/lib/components/apps/editor/inlineScriptsPanel/InlineScriptsPanel.svelte
frontend/src/lib/components/apps/editor/inlineScriptsPanel/InlineScriptsPanelList.svelte
frontend/src/lib/components/common/fileInput/FileInput.svelte
frontend/src/lib/components/common/tabs/Tab.svelte
frontend/src/lib/components/common/tabs/Tabs.svelte

Added CSS customisation options to the following app components:
- number input
- currency input
- slider
- range
- password input
- date input
- tabs
- icon
- horizontal divider
- vertical divider
- file input
- image

fix(frontend): Add more app custom css

---

frontend/src/lib/components/apps/editor/contextPanel/ContextPanel.svelte
frontend/src/lib/components/propertyPicker/ObjectViewer.svelte

feat(frontend): Fix object viewer style

---

frontend/src/lib/components/common/menu/Menu.svelte
frontend/src/lib/components/home/ItemsList.svelte

Fix the z-index issue in the main side menu:

fix(frontend): Side menu z-index issue

---

frontend/src/lib/components/apps/components/buttons/AppButton.svelte
frontend/src/lib/components/apps/components/display/AppIcon.svelte
frontend/src/lib/components/apps/editor/AppEditor.svelte
frontend/src/lib/components/apps/editor/AppEditorHeader.svelte
frontend/src/lib/components/apps/editor/componentsPanel/ComponentList.svelte
frontend/src/lib/components/apps/editor/contextPanel/ContextPanel.svelte
frontend/src/lib/components/apps/editor/inlineScriptsPanel/InlineScriptsPanelList.svelte
frontend/src/lib/components/apps/editor/settingsPanel/GridPane.svelte
frontend/src/lib/components/apps/editor/settingsPanel/GridTab.svelte
frontend/src/lib/components/apps/editor/settingsPanel/inputEditor/IconSelectInput.svelte
frontend/src/lib/components/common/tabs/Tabs.svelte

Did the following changes:
- applied consistent styling to the "undo"/"redo" buttons
- aligned the right pane tab row (insert, settings, css)
- removed empty categories from component search
- added animations to searches (components and outputs panel)
- updated "runnables" typography
- added "clear" button to the icon picker input
- fixed minor inconsistencies

fix(frontend): Clean up app editor

---

frontend/src/lib/components/apps/editor/contextPanel/ContextPanel.svelte

Fixing z-index issue of the search bar in the outputs panel

fix(frontend): Display app context search on top

---

docker-compose.yml

I found that Windmill has mapped three unnecessary external ports binding to the host, including the port for Postgres, which is not needed and also very dangerous.
After deployment, I noticed many brute force login attempts:
```
windmill-db-1               | 2023-04-05 03:05:23.291 UTC [32142] FATAL:  password authentication failed for user "postgres"
windmill-db-1               | 2023-04-05 03:05:23.291 UTC [32142] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
windmill-db-1               | 2023-04-05 03:05:26.365 UTC [32143] FATAL:  password authentication failed for user "postgres"
windmill-db-1               | 2023-04-05 03:05:26.365 UTC [32143] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
```
Communication …

fix: no need to map internal ports to hosts

---

frontend/src/lib/components/Popover.svelte

Changed the configuration to avoid content shift:
Before:
After:

fix(frontend): fix popover configuration to avoid content shift

---

frontend/src/lib/components/ScriptBuilder.svelte
frontend/src/routes/(root)/(logged)/scripts/add/+page.svelte

Not sure if this is the best way to go about this, but in a previous iteration of the UI we were able to deep link to `/scripts/add` with a state variable to pop someone into the script editor with some default script content and still leverage the default path and naming that windmill provided.  With the latest changes if any `state` is provided you no longer go through the metadata step and we end up with some undefined variables in the meta unless you click somewhere to trigger the drawer.  
Just looking for a way to get a similar flow in the current version where we can send some default script content in a link that will create a new script -- but still leverage the default script naming and path selection that windmill was providing. This will force the drawer to open if a …

feat(frontend): support showing metadata on script add via query param

---

frontend/src/routes/(root)/(logged)/workspace_settings/+page.svelte

Same typo [on the pricing page](https://www.windmill.dev/pricing)

chore: fix typo

---

Dockerfile
docker/DockerfileHelm
docker/DockerfileOpenbb

PR adds a symlink towards the end of the docker build process so that `windmill` command can be called directly from the path. Also removes the `./windmill` for the last `CMD` line since `windmill` is now within the `PATH` environment variable.

fix: Add symlink to dockerfile

---

frontend/src/lib/components/TestConnection.svelte

Fix #1775 
tested with:
1. setup fresh postgres15.3 container with `POSTGRES_PASSWORD` `kot@behemot#zonk`
2. get DB URI with
```javascript
const args = { user: 'postgres', password: 'kot@behemot#zonk', host: '0.0.0.0', dbname: 'postgres', sslmode: 'disable' };
const u = new URL(`postgres://${args.user}:${args.password}@${args.host}:${args.port ?? 5432}/${args.dbname}?sslmode=${args.sslmode}`);
u.hash = '';
u.search = `?sslmode=${args.sslmode}`;
u.pathname = args.dbname;
u.host = args.host;
u.password = args.password;
u.username = args.user;
u.toString();
```
3. connect to db
```console
psql 'postgres://postgres:kot%40behemot%23zonk@0.0.0.0/postgres?sslmode=disable'
```

fix(frontend): support special chars in postgresql client [#1775]

---

backend/Cargo.toml

According to https://github.com/launchbadge/sqlx/blob/main/CHANGELOG.md, sqlx version 0.7.0 is kind of a big jump in terms of features and breaking changes. We should probably stick to 0.6.X. I tried using 0.7.0 by mistake and for example the generation of sqlx-data.json wasn't working properly

chore: Force sqlx version to remain <0.7.0

---

frontend/src/lib/components/SchemaEditor.svelte
frontend/src/routes/(root)/(logged)/resources/+page.svelte

When viewing schema as JSON and adding property via the "Add property button", JSON schema would not show the newly added property. PR fixes this behavior.
Minor layout tweaks to remove unnecessary whitespace and scroll jitter.

fix: add property while viewing as JSON (+ ui tweaks)

---

frontend/src/lib/components/SchemaEditor.svelte

Fixing : Adding property to a nested object would give error 'jsonEditor undefined'.

fix: prevent error if json editor not mounted

---

frontend/src/lib/components/SchemaModal.svelte

Handling enter key was breaking:
- Inserting line breaks in description (modal would close)
- Nested property edit (all nested modals would close at once)
Now enter works only when name input is focused but experience is overall less surprising.

fix: schema modal behavior when pressing enter

---

backend/parsers/windmill-parser-py-imports/src/lib.rs

Add python import replacement for google-api-python-client. See: https://github.com/googleapis/google-api-python-client

Add another pip import replacement

---

frontend/src/lib/components/apps/components/inputs/AppSelect.svelte
frontend/src/lib/components/apps/editor/component/components.ts

Fix #1998 for the Select Input component:
This was surprisingly simple! Let me know of any issues.

feat(frontend): add disabled prop to select input

---

frontend/src/lib/components/AddUser.svelte
frontend/src/lib/components/InviteUser.svelte
frontend/src/lib/components/settings/WorkspaceUserSettings.svelte

Just a small change as I noticed when adding users of my team who are female that 3 tooltips were gender specific.  nbd

make tooltips non-gender specific

---

backend/parsers/windmill-parser-py-imports/src/lib.rs

`import dateutil`
```
dateutil can be installed from PyPI using pip (note that the package name is different from the importable name):
```
- https://pypi.org/project/python-dateutil/

Add dateutil => python-dateutil to PYTHON_IMPORTS_REPLACEMENT

---

backend/windmill-api/src/oauth2.rs
backend/windmill-common/src/more_serde.rs

This change allows parsing expires_in from a string while also retaining its previous behavior
This works for the following cases:
- the json response contains `expires_in` as a numeric value (as expected before)
- the json response contains `expires_in` as a string 
- the json response does not contain `expires_in` at all

feat(backend): parse expires_in from string in TokenResponse

---

frontend/src/lib/components/copilot/FlowCopilotDrawer.svelte
frontend/src/lib/components/copilot/flow.ts

fix: ai flow prompt fix + explanation in ui

---

frontend/src/lib/components/apps/editor/componentsPanel/CssProperty.svelte
frontend/src/lib/components/apps/editor/componentsPanel/QuickStyleMenu.svelte
frontend/src/lib/components/apps/editor/componentsPanel/QuickStyleProperty.svelte

feat(frontend): fix css editor + fix dark mode

---

.github/workflows/docker-image.yml

The windmill binary will be extracted from the built docker image, renamed and uploaded to the release.

build: Publish windmill-amd64 binary for each release

---

backend/windmill-worker/src/worker_flow.rs

This pull request introduces a bug fix where previously, a non-integer value
provided for the sleep duration would be silently ignored because `as_u64()`
would return `None` when `n` was a float, leading to an unintended skip over the
sleep behavior.

fix: fail on non-integer sleep value

---

frontend/src/lib/components/SuperadminSettings.svelte
frontend/src/lib/components/UserSettings.svelte

Closing the Instance settings and user settings with drawer with escape wouldn't remove the hash from the URL, resulting into a state we couldn't open any of those two menu again.
Clicking away also fires the `on:close` event.

fix(frontend): escape wasn't removing the hash when closing a drawer

---

backend/parsers/windmill-parser-py-imports/src/lib.rs

Adding OpenCV to Python install/import exceptions mapping
OpenCV URL: https://pypi.org/project/opencv-python/
You install the package with `pip install opencv-python`, and import with `import cv2`

Update lib.rs with cv2

---

python-client/wmill/wmill/client.py

This script updates the `wmill` client to add additional arguments to the methods for running scripts synchronously.
* `assert_result_is_not_none`
* `cleanup`
* `timeout`
`assert_result_is_not_none` asserts that the result of the script isn't null. The current behavior is to raise an exception if the result is falsey, which causes unnecessary failures if the result is something like 0, probably a bug.
`cleanup` ensures that jobs that are cancelled gracefully when the parent script is cancelled.
`timeout` throws a `TimeoutError` if passed and the script takes longer than it to execute

feat(python): Add functionality and resiliency to wmill python client

---

backend/parsers/windmill-parser-py-imports/src/lib.rs

The official Atlassian python library is named `atlassian-python-api`, which requires an installation under that name. It is imported as `atlassian`.

Add official Atlassian Python Library Mapping

---

python-client/wmill/README.md

In the README's example code for the wmill Python client, the method name `start_execution` has been changed to `run_script_async`. This change is in line with the recent updates we made to the client's public API.

chore(documentation): Update method name in wmill python README sample code

---

python-client/wmill/wmill/client.py

This fixes references that are no longer valid to `Windmill.start_execution`. They now currently point to `Windmill.run_script_async`

bug(python): Fix references to `Windmill.start_script_async`

---

python-client/wmill/wmill/client.py

This PR helps prevent a bug wherein a script that fails (not cancelled) DOESN'T cause the parent script to fail

bug(python): Corrently handle terminal state when invoking job through `run_script` method

---

backend/tests/worker.rs

The actual fix for the GOROOT error we were seeing on CI is here: https://github.com/windmill-labs/windmill/pull/2814, but this makes the test more robust

fix: test_complex_flow_restart running a constantly failing flow on CI

---

python-client/wmill/wmill/client.py

This commit introduces a change in the Windmill class constructor (in wmill/client.py) to include `workspace` as a parameter. 
It's especially useful when interfacing with the windmill server externally combined with the `base_url` parameter.

feat(python): Updated Windmill client constructor to accept workspace

---

frontend/src/lib/components/InstanceSettings.svelte
frontend/src/lib/components/KanidmSetting.svelte
frontend/src/lib/components/icons/KanidmIcon.svelte
frontend/src/lib/components/icons/index.ts

Following the addition of support for Authelia SSO via #2824, this PR adds support for [Kanidm](https://kanidm.com/) SSO.
This one was _slightly_ more complex than most other custom SSO providers, as Kanidm's endpoint for user info isn't just a prefix (i.e. subdomain), but instead requires the `client_id` deeper within the path (i.e. `https://id.some-domain.com/oauth2/openid/:client_id:/userinfo`, [ref](https://kanidm.github.io/kanidm/master/integrations/oauth2.html#resource-server)), so there's a bit more interpolation. Nothing too scary though :)

feat: Add Kanidm SSO support

---

backend/windmill-worker/src/python_executor.rs

We can now safely do:
```python
def main():
exit()
```

fix: Python wrapper catches BaseException instead of Exception

---

frontend/src/lib/components/flows/content/FlowInputs.svelte

fix: spelling error dtails -> details

---

lsp/Dockerfile

Currently /tmp/monaco ends up only writable by root, as build context runs as root, and read-only by other users. 
Running the image with a non-root uid fails, as launcher fails to write out go.mod to the root owned directory.
Some environments do not allow running things as root.

feat: Allow running image as non-root user

---

backend/windmill-worker/src/deno_executor.rs

This PR adds the `--unstable-http` arg to deno in deno executor. This flag allows the use of `--unstable-http`
https://github.com/denoland/deno/issues/22155

fix: add --unstable-http arg to deno in deno executor

---

backend/windmill-worker/src/python_executor.rs

- URLs that contain simple auth seem to have that stripped before being passed to underlying pip if it needs to be called by pip-compile.
- This forces explicit passing of the complete, authenticated url string to pip, through pip-compile, via pip-compile's "--pip-args" argument.

Properly handle pip index urls in pip-compile

---

backend/Cargo.lock
backend/Cargo.toml

Updated to a newer patch of RustPython so the nightly compiler now also works (see https://github.com/RustPython/Parser/pull/111). Of course, the stable compiler also still works correctly. I also needed to change the version of the time crate to fix version mismatches across dependencies. The only two changes are to
(1) `Cargo.toml`, which was a manual version change. Note that RustPython has not had a tagged version update since this nightly fix, so we use the GitHub commit.
```bash
-rustpython-parser = "0.3.0"
+rustpython-parser = { git = "https://github.com/RustPython/Parser", rev = "29c4728dbedc7e69cc2560b9b34058bbba9b1303" }
```
(2) `Cargo.lock`, which was the result of a `cargo update`:
```bash
error: failed to select a version for `time`.
... required by package …
```

Fix nightly rustc compilation: update RustPython dependency

---

backend/windmill-api/src/settings.rs
backend/windmill-api/src/users.rs

The library currently loads fixed set of certificates from a rust package, does not use OS certificate store. Providing a custom CA would need to be done via a custom tls connector.
Would appreciate a patch release with this, so I can pick up the change via official channels 🙇

feat: Use ACCEPT_INVALID_CERTS for SMTP

---

examples/deploy/aws-ecs-terraform/ecs_cluster.tf

Previous AMI no longer exists, updated to latest Amazon Linux 2023

Update AMI used in aws-ecs-terraform example

---

backend/parsers/windmill-parser-py-imports/src/lib.rs

Discussion: https://discord.com/channels/930051556043276338/1231984078211776532/1231984078211776532
In summary:
```import haystack_ai as haystack```
Installs properly, but after installation will raise the following
```
<module>
import haystack_ai as haystack
ModuleNotFoundError: No module named 'haystack_ai'
```
And attempting to change the import to `haystack` it will point to other installation.

import replacement: haystack >> haystack-ai

---

backend/.sqlx/query-202a4fee4e70ff74d150a187a8daec3609328b1e3fe6e4fac20fb6fe91ff1732.json
backend/.sqlx/query-337f31c2172194cd594042c561998a03f751b246c40daf056fced0fd91f6dd73.json
backend/.sqlx/query-4996b5af348bc335a5ec14496683cee096e37bdde7bb05c11ee0c4792f70dc60.json
backend/.sqlx/query-4b923c94f6adcc7a76e8073de5e46b116dba3211487c8408ce2777aafdf94a44.json
backend/.sqlx/query-4bbf4dbf5b18d8dfd62c0a029ec4deb95a348dc804ee23a02698adb9aa32b375.json
backend/.sqlx/query-63e54fe57ec439b68eead00a02209f81076c5317d590e1441b557555b4d7ad96.json
backend/.sqlx/query-6673aeb02e1c39616c6f38fd2bad841271bc08401573f4d1be8e8896cd77507b.json
backend/.sqlx/query-a0a97ad8c36356407f13e6b429d923f59d18743efc77e44abc57632252488160.json
backend/.sqlx/query-a1a339c9e744b5661d2b4d1354e593b97b4e007fa9a499b49c3d1ebf9b645a3b.json
backend/.sqlx/query-c05f21e7027a985e5a657b689a0f5bedefcaa15b7887402c0d5d33cb7b5fb362.json
backend/.sqlx/query-e0e895527d6807699c918ca87e0b016751c9b5a1dab632dc4abdb1dd6aa1fcbc.json
backend/.sqlx/query-f5c94d89eb8c86916d7c64ffa8ea2de1feecbfde74e9a1374b3668ec72d7bac1.json
backend/migrations/20241119062608_create_job_and_views.down.sql
backend/migrations/20241119062608_create_job_and_views.up.sql
backend/windmill-api/src/jobs.rs
backend/windmill-common/src/flows.rs
backend/windmill-common/src/jobs.rs
backend/windmill-common/src/worker.rs
backend/windmill-queue/src/jobs.rs
backend/windmill-worker/src/worker.rs
backend/windmill-worker/src/worker_flow.rs
backend/windmill-worker/src/worker_lockfiles.rs

This change aims to reduce the row size of the `queue` and `completed_job` tables by migrating "persistent" columns (i.e., columns not directly associated with runtime status) to a new shared `job` table. Both queued and completed jobs will reference this table, leading to significantly faster updates on the `queue` table.
- **Database integrity**: Original columns from `queue` and `completed_job` are left in place but will remains empty after the upgrade in complete.
- **Handling Legacy Workers**: After the upgrade, legacy workers (those running a previous version of the codebase) may still be operational. To maintain compatibility, the migrated columns will continue to be inserted into the `queue` table until all workers are updated ([Reference: …

feat(backend): move some static fields out of job tables

---

frontend/src/lib/components/common/confirmationModal/DeployOverrideConfirmationModal.svelte

The grammar in the confirmation modal was a little wonky

Fix wording in DeployOverrideConfirmationModal.svelte
