windmill-labs/windmill

- backend/openapi.yaml
- backend/src/flows.rs
- backend/src/worker_flow.rs
- frontend/src/lib/components/flows/utils.ts
Superseeding @sqwishy #257 
No UI integration for now, just hardcoded into the UI that this is always the case. Easy to revise later. It's a better default than the opposite.
> feat: skip failures loop

- frontend/src/lib/components/ScriptEditor.svelte
Fix the script editor styling issues.
> Fix EditorBar in the script editor

- frontend/src/app.css
- frontend/src/lib/components/CenteredPage.svelte
- frontend/src/lib/components/FlowBuilder.svelte
- frontend/src/lib/components/FlowEditor.svelte
- frontend/src/lib/components/FlowPreviewContent.svelte
- frontend/src/lib/components/FlowStatusViewer.svelte
- frontend/src/lib/components/InputTransformForm.svelte
- frontend/src/lib/components/JobStatus.svelte
- frontend/src/lib/components/ObjectResourceInput.svelte
- frontend/src/lib/components/SchemaEditor.svelte
- frontend/src/lib/components/ScriptBuilder.svelte
- frontend/src/lib/components/flows/FlowSettings.svelte
- frontend/src/routes/__layout@root.svelte
- Added a flow preview sidebar
> Flow preview

- frontend/src/lib/components/FlowBuilder.svelte
Fix flow preview, and made sure it's closed when going to the second step
> Fix flow preview + correct stylee

- backend/src/db.rs
- backend/src/lib.rs
If unspecified, defaults to the current value of 100
> DATABASE_CONNECTIONS sets Pool max_connections

- Dockerfile
- backend/.cargo/config
https://github.com/rust-lang/rust/issues/39915
Mostly improves incremental rebuilds, like linking windmill lib.
> link with lld

- backend/Cargo.lock
- backend/Cargo.toml
- backend/src/external_ip.rs
- backend/src/lib.rs
Also a warning if it fails instead of failing silently, but if we don't want that I can remove it.
> ping hub.windmill.dev/getip for external ip

- frontend/src/routes/flows.svelte
- frontend/src/routes/scripts.svelte
I have read the CLA Document and I hereby sign the CLA
> Typo: explicitely -> explicitly

- backend/openapi.yaml
- backend/src/parser.rs
- backend/src/parser_py.rs
- backend/src/parser_ts.rs
- frontend/src/lib/common.ts
- frontend/src/lib/components/ArgInput.svelte
- frontend/src/lib/components/InputTransformForm.svelte
- frontend/src/lib/components/ResourceEditor.svelte
- frontend/src/lib/components/SchemaForm.svelte
- frontend/src/lib/infer.ts
> feat: add literal object type support

- .env
- Caddyfile
- docker-compose.yml
related to https://github.com/windmill-labs/windmilldocs/pull/12 
- Adds root `Caddyfile`
- Adds LSP to `compose` 
- Adds Caddy to `compose` and uses the `Caddyfile`
> feat: add lsp and caddy

- frontend/src/lib/components/ModuleStep.svelte
- frontend/src/lib/components/flows/FlowBox.svelte
- frontend/src/lib/components/flows/FlowBoxHeader.svelte
- frontend/src/lib/components/flows/FlowInput.svelte
- frontend/src/lib/components/flows/FlowModuleHeader.svelte
- frontend/src/lib/components/flows/FlowSettings.svelte
- frontend/src/lib/components/flows/utils.ts
https://user-images.githubusercontent.com/456655/185177064-c963c0c6-326b-4ee9-8342-0e6cfcf56293.mov
> feat(frontend): Open/Close UI

- backend/src/jobs.rs
- backend/src/worker.rs
- backend/src/worker_flow.rs
usize as u8 will mask out the higher bits, so 0x100 as u8 is 0x00, 0x101
is 0x01 and only iterates once, etc....
refactors push_next_flow_job a bit
> fixes forloop with 257 items only iterates once

- frontend/src/lib/components/landing/FlowGettingStarted.svelte
- frontend/src/lib/components/landing/FlowLandingBox.svelte
- frontend/src/lib/components/landing/RessourceGettingStarted.svelte
- frontend/src/lib/components/landing/ScriptBox.svelte
- frontend/src/lib/components/landing/ScriptGettingStarted.svelte
- frontend/src/routes/__layout@root.svelte
- frontend/src/routes/index.svelte
> feat(frontend): App landing page

- frontend/src/lib/components/jobs/JobDetail.svelte
- frontend/src/lib/components/landing/FlowGettingStarted.svelte
- frontend/src/lib/components/landing/ScriptGettingStarted.svelte
- frontend/src/routes/index.svelte
- frontend/src/routes/runs/[...path].svelte
> feat(frontend): Add runs to landing page + fix responsive issues

- frontend/src/lib/components/FlowPreviewContent.svelte
> fix(frontend): Fix flow preview inputs display to avoid hiding results

- frontend/src/lib/components/flows/content/FlowEditorPanel.svelte
- frontend/src/lib/components/flows/content/FlowRetries.svelte
- frontend/src/lib/components/flows/content/FlowSettings.svelte
- frontend/src/lib/components/flows/header/FlowPreviewButtons.svelte
- frontend/src/lib/components/flows/header/FlowStatus.svelte
> feature(frontend): Add support for retries for flows

- frontend/src/lib/components/ArgInput.svelte
- frontend/src/lib/components/FlowBuilder.svelte
- frontend/src/lib/components/FlowPreview.svelte
- frontend/src/lib/components/FlowPreviewContent.svelte
- frontend/src/lib/components/FlowStatusViewer.svelte
- frontend/src/lib/components/InputTransformForm.svelte
- frontend/src/lib/components/flows/FlowEditor.svelte
- frontend/src/lib/components/flows/content/CopyFirstStepSchema.svelte
- frontend/src/lib/components/flows/content/FlowEditorPanel.svelte
- frontend/src/lib/components/flows/content/FlowLoop.svelte
- frontend/src/lib/components/flows/content/FlowModule.svelte
- frontend/src/lib/components/flows/content/FlowModuleWrapper.svelte
- frontend/src/lib/components/flows/flowState.ts
- frontend/src/lib/components/flows/flowStateUtils.ts
- frontend/src/lib/components/flows/header/FlowStatus.svelte
- frontend/src/lib/components/flows/map/FlowModuleSchemaItem.svelte
- frontend/src/lib/components/flows/map/FlowModuleSchemaMap.svelte
- frontend/src/routes/run/[...run].svelte
The flow is no more duplicated in the flowState and flowStore is the source of truth. Also fix all previews, also small fixes.
> fix flow UX and flowStateStore

- frontend/src/lib/components/EditorBar.svelte
- frontend/src/lib/components/FlowBuilder.svelte
- frontend/src/lib/components/ScriptEditor.svelte
- frontend/src/lib/components/common/button/Button.svelte
- frontend/src/lib/components/flows/header/FlowImportExportMenu.svelte
- frontend/src/lib/components/flows/header/FlowPreviewButtons.svelte
- frontend/src/lib/utils.ts
First iteration of the Button component.
> feature(frontend): Button component

- frontend/src/lib/components/SharedBadge.svelte
- frontend/src/lib/components/Tooltip.svelte
- frontend/src/lib/components/common/badge/Badge.svelte
- frontend/src/lib/components/common/badge/model.ts
- frontend/src/lib/utils.ts
- frontend/src/routes/scripts/get/[...hash].svelte
Created a common Badge component, fixed the inconsistensies of the tooltip text and implemented a new design for the script detail page.
**Button functionalities on script page are unchanged in this PR.**
**Desktop:**
**Mobile:**
> feat(frontend): Badge component and script page

- frontend/src/lib/components/FlowPreview.svelte
- frontend/src/lib/components/flows/content/FlowModule.svelte
> feat(frontend): Add a split panel in the test tab

- frontend/src/lib/components/FlowBuilder.svelte
- frontend/src/lib/components/flows/header/FlowImportExportMenu.svelte
> feat(frontend): Extract publish to hub button

- frontend/src/lib/components/ScriptEditor.svelte
- frontend/src/lib/components/common/tabs/Tabs.svelte
- frontend/src/lib/components/script_editor/LogPanel.svelte
- frontend/src/routes/user/login@user.svelte
> feat(frontend): merge logs and result tab in script editor

- backend/Cargo.lock
> update cron v0.12.0

- frontend/src/lib/components/EditorBar.svelte
- frontend/src/lib/components/FlowBuilder.svelte
- frontend/src/lib/components/ModulePreview.svelte
- frontend/src/lib/components/common/button/Button.svelte
- frontend/src/lib/components/flows/header/FlowImportExportMenu.svelte
- frontend/src/routes/flows/get/[...path].svelte
- frontend/src/routes/scripts/get/[...hash].svelte
- Add a custom spacing when necessary, and revert some styling changes.
> fix(frontend): Fix buttons spacings

- frontend/src/lib/components/Editor.svelte
- frontend/src/lib/components/EditorBar.svelte
- frontend/src/lib/components/flows/content/FlowModule.svelte
> feat(frontend): Add contextual actions to insert variables or resources

- frontend/src/lib/components/common/actionRow/ActionRow.svelte
- frontend/src/lib/components/common/button/Button.svelte
- frontend/src/lib/components/flows/flowStateUtils.ts
- frontend/src/lib/components/icons/HatIcon.svelte
- frontend/src/lib/components/landing/FlowGettingStarted.svelte
- frontend/src/lib/components/landing/RessourceGettingStarted.svelte
- frontend/src/lib/components/landing/ScriptBox.svelte
- frontend/src/lib/components/landing/ScriptGettingStarted.svelte
- frontend/src/routes/flows/get/[...path].svelte
- frontend/src/routes/scripts/get/[...hash].svelte
- Use common components ( Button, Badge)
> feat(frontend): Landing rework

- frontend/src/lib/components/flows/content/FlowModule.svelte
- frontend/src/lib/components/flows/content/FlowModuleHeader.svelte
- frontend/src/lib/components/flows/content/FlowModuleScript.svelte
> fix(frontend): Hide the editor panel when we are editing a PathScript

- frontend/src/lib/components/EditorBar.svelte
- frontend/src/lib/components/IconedPath.svelte
- frontend/src/lib/components/ModulePreview.svelte
- frontend/src/lib/components/common/button/Button.svelte
- frontend/src/lib/components/flows/FlowEditor.svelte
- frontend/src/lib/components/flows/common/FlowCard.svelte
- frontend/src/lib/components/flows/common/FlowCardHeader.svelte
- frontend/src/lib/components/flows/content/FlowModule.svelte
- frontend/src/lib/components/flows/content/FlowModuleHeader.svelte
- frontend/src/lib/components/flows/header/FlowEditorHeader.svelte
- frontend/src/lib/components/flows/map/FlowModuleSchemaItem.svelte
- frontend/src/lib/components/flows/map/FlowModuleSchemaMap.svelte
- frontend/src/lib/components/flows/propPicker/PropPickerWrapper.svelte
> feat(front): Rework how summaries are edited in the flow editor

- frontend/src/lib/components/Dropdown.svelte
- frontend/src/lib/components/flows/content/RemoveStepConfirmationModal.svelte
- frontend/src/lib/utils.ts
- frontend/src/routes/resources.svelte
- frontend/src/routes/variables.svelte
https://user-images.githubusercontent.com/456655/193264399-b1faaa45-acf8-4ee6-8d92-f38161449cf9.mov
> feat(front): Confirmation modal when deleting a resource or a variable

- frontend/src/lib/components/TestJobLoader.svelte
> fix(frontend): don't loop for completed jobs [#649]

- backend/src/flows.rs
- backend/src/worker.rs
- backend/src/worker_flow.rs
- frontend/src/lib/components/FlowPreviewContent.svelte
- frontend/src/lib/components/FlowStatusViewer.svelte
- frontend/src/lib/components/InputTransformForm.svelte
- frontend/src/lib/components/SchemaForm.svelte
- frontend/src/lib/components/flows/content/FlowLoop.svelte
- frontend/src/lib/components/flows/content/FlowModule.svelte
- frontend/src/lib/components/flows/content/FlowModuleSuspend.svelte
- frontend/src/lib/components/flows/flowStateUtils.ts
- frontend/src/lib/components/flows/propPicker/PropPickerWrapper.svelte
- frontend/src/lib/components/flows/utils.ts
- frontend/src/lib/components/propertyPicker/PropPicker.svelte
- openflow.openapi.yaml
> feat: sleep for arbitrary number of seconds statically or with a javascript expression

- frontend/src/lib/components/common/skeleton/Skeleton.svelte
- frontend/src/lib/components/common/skeleton/SkeletonElement.svelte
- frontend/tailwind.config.cjs
Removed the delay and updated the animation to start from 0 opacity.
> fix(frontend): Update skeleton animation timings

- frontend/src/routes/user/workspaces@user.svelte
Updated the workspace selector view.
**Desktop:**
**Mobile:**
> feat(frontend): Update workspace selector style

- backend/src/flows.rs
- backend/src/worker.rs
- backend/src/worker_flow.rs
- openflow.openapi.yaml
also move BranchOne to use embedded flow instead of slicing into main flow hack
> feat(backend): add branch all

- backend/src/audit.rs
- backend/src/users.rs
- backend/src/worker.rs
This simply adds a handful of extra tracing spans. All are at the trace level.
> Add more tracing

- benchmarks/main.ts
- benchmarks/worker.ts
Minor Bench improvements. Fixes minor issues I encountered and adds --continous, allowing infinite testing without consuming infinite memory.
> Bench improvements

- deno-client/mod.ts
UC:
> as a windmill script developer I want to know what type/data structure is returned from the windmill sdk
> feat(deno-client): improve docs by extending function signatures

- benchmarks/Dockerfile
Adds a dockerfile to the benchmarks directory, to deploy the benchmark tool as docker container.
> feat(benchmarks): dockerfile

- frontend/src/lib/components/flows/map/FlowModuleSchemaItem.svelte
> fix(frontend): Fix overlay map indicator

- cli/flow.ts
- cli/resource.ts
- cli/script.ts
- cli/user.ts
- cli/variable.ts
There are some other minor things, but these are the basic fixes that we really care about.
- Fixes Infinite user list
- Remove descriptions from tables
> Cli improvements

- benchmarks/action.ts
- benchmarks/example_fake_user.json
- benchmarks/main.ts
- benchmarks/worker.ts
This adds an option to allow defining custom actions to execute during benchmarking. This is useful to generate more realistic workloads.
> feat(benchmarks): Allow complex action setups in benchmarks

- frontend/src/lib/components/flows/FlowEditor.svelte
- frontend/src/lib/components/flows/map/FlowErrorHandlerItem.svelte
- frontend/src/lib/components/flows/map/FlowModuleSchemaMap.svelte
- frontend/src/lib/components/flows/map/FlowSettingsItem.svelte
https://user-images.githubusercontent.com/456655/201636256-fe33f187-383f-4847-ac3a-ed816b497005.mov
> fix(frontend): Set settings as header and error handler as footer

- frontend/src/routes/scripts/run/[...hash].svelte
> Deployement -> Deployment

- frontend/src/lib/components/SchemaForm.svelte
- frontend/src/lib/components/apps/components/charts/PieChartComponent.svelte
- frontend/src/lib/components/apps/components/helpers/InputValue.svelte
- frontend/src/lib/components/apps/components/helpers/RunnableComponent.svelte
- frontend/src/lib/components/apps/components/helpers/RunnableInputValue.svelte
- frontend/src/lib/components/apps/editor/ComponentEditor.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/data.ts
- frontend/src/lib/components/apps/editor/contextPanel/ComponentOutputViewer.svelte
- frontend/src/lib/components/apps/rx.ts
- frontend/src/lib/components/apps/types.ts
- frontend/src/lib/components/common/alert/Alert.svelte
https://user-images.githubusercontent.com/456655/203332486-3a8eeeb1-2b7e-41b4-aa68-8c88c389a64b.mov
> Runnable refactor

- backend/windmill-worker/src/worker.rs
I would've prefered to fix this "upstream" by passing the python code through normally and handling the parsing in the worker, but this was much easier and doesn't involve breaking data.
> Fix Python flow lock

- frontend/src/lib/components/apps/editor/contextPanel/ContextPanel.svelte
- frontend/src/lib/components/common/drawer/Drawer.svelte
> feat(frontend): Add guard against script overwrite

- frontend/src/lib/components/VariableEditor.svelte
- frontend/src/routes/scripts/get/[...hash].svelte
> feat(frontend): rework script detail

- community/resource_types/mysql.json
Two line change to remove postgres from the MySQL resource.
> Remove postgres wording from mysql resource

- frontend/src/lib/components/SimpleEditor.svelte
- frontend/src/lib/components/apps/components/dataDisplay/AppTable.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/data.ts
- frontend/src/lib/components/apps/editor/contextPanel/ContextPanel.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/ComponentPanel.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/StaticInputEditor.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/TableActions.svelte
> feat(frontend): Add support for object editor + fix wording

- frontend/src/lib/components/apps/editor/AppEditorHeader.svelte
- frontend/src/lib/components/apps/editor/inlineScriptsPanel/InlineScriptsPanel.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/ComponentPanel.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/Recompute.svelte
- frontend/src/lib/components/apps/utils.ts
- Fix Recompute section
- Clean up the alignement section
- Fix Toggle component ( rename Checkbox in Toggle)
- Fix component icons
> feat(frontend): Small UI fixes

- frontend/src/lib/components/apps/editor/inlineScriptsPanel/InlineScriptEditor.svelte
- frontend/src/lib/components/apps/editor/inlineScriptsPanel/InlineScriptsPanel.svelte
- frontend/src/lib/components/apps/editor/inlineScriptsPanel/InlineScriptsPanelList.svelte
https://user-images.githubusercontent.com/456655/208609725-b97a33c9-bd7b-4476-b825-e5b6cd9e58f4.mov
> feat(frontend): Add an input field to edit inline script name

- frontend/src/lib/components/apps/editor/ComponentEditor.svelte
- frontend/src/lib/components/apps/editor/ComponentHeader.svelte
- frontend/src/lib/components/apps/editor/GridEditor.svelte
- frontend/src/lib/components/apps/gridUtils.ts
https://user-images.githubusercontent.com/456655/208689703-e2401fac-88ab-4af9-8fb6-45369846d35c.mov
> feat(frontend): Add the ability to lock components

- backend/Cargo.lock
- backend/windmill-api/openapi.yaml
- backend/windmill-api/src/jobs.rs
- backend/windmill-queue/src/jobs.rs
- frontend/src/lib/components/FlowPreviewContent.svelte
- frontend/src/lib/components/FlowStatusViewer.svelte
- frontend/src/lib/components/InputTransformForm.svelte
- frontend/src/lib/components/TemplateEditor.svelte
- frontend/src/lib/components/flows/content/FlowModuleScript.svelte
- frontend/src/lib/components/flows/header/FlowPreviewButtons.svelte
- frontend/src/lib/components/flows/previousResults.ts
- frontend/src/lib/components/propertyPicker/PropPicker.svelte
- frontend/src/lib/utils.ts
> feat(backend): resume from owner directly in flow status viewer

- frontend/src/lib/components/sidebar/SidebarContent.svelte
- frontend/src/routes/(root)/(logged)/+layout.svelte
- fixed logo overflow when menu is collapsed
- fixed spacing of menu items
- updated folders icon
> feat(app): Update sidebar menu

- frontend/src/lib/components/Dropdown.svelte
- frontend/src/lib/components/Star.svelte
- frontend/src/lib/components/common/table/AppRow.svelte
- frontend/src/lib/components/common/table/FlowRow.svelte
- frontend/src/lib/components/common/table/Row.svelte
- frontend/src/lib/components/common/table/ScriptRow.svelte
- frontend/src/lib/components/home/ItemsList.svelte
- frontend/src/lib/components/sidebar/FavoriteMenu.svelte
- frontend/src/lib/components/sidebar/WorkspaceMenu.svelte
- frontend/src/routes/(root)/(logged)/+layout.svelte
- fix weird off pixels and lines in home page list items
- update dropdown button
- update starring button
- make sidebar popup menus consistent
> fix(app): Fix inconsistencies in list items and sidebar menus

- frontend/src/lib/components/InputTransformForm.svelte
- frontend/src/lib/components/Popover.svelte
- frontend/src/lib/components/SchemaForm.svelte
- frontend/src/lib/components/ScriptEditor.svelte
- frontend/src/lib/components/TemplateEditor.svelte
- frontend/src/lib/components/flows/content/FlowModuleHeader.svelte
- frontend/src/lib/components/flows/map/FlowModuleSchemaItem.svelte
- fixed overflow issue in the arguments pane of the script editor page
- fixed font size inconsistency of the argument editors on the flow editor page
- fixed script 'advanced' settings inconsistencies and added tooltip to buttons (sleep, break, suspen, sleep)
> fix(frontend): Minor fixes in editor

- frontend/src/lib/components/flows/content/FlowConstants.svelte
- frontend/src/lib/components/flows/map/FlowConstantsItem.svelte
- frontend/src/lib/components/flows/map/FlowModuleSchemaMap.svelte
- frontend/src/lib/components/flows/map/FlowSettingsItem.svelte
- fixed hidden overflow on static inputs panel
- updated panel selector button
> fix(frontend): Static inputs overflow

- frontend/src/lib/components/ArgInput.svelte
- frontend/src/lib/components/InputTransformForm.svelte
- frontend/src/lib/components/flows/content/FlowConstants.svelte
> feat(frontend): Add toggle to hide optional static flow inputs

- frontend/src/lib/components/Dropdown.svelte
- frontend/src/lib/components/apps/editor/RecomputeAllComponents.svelte
> feat(frontend): Update app auto-refresh button

- frontend/src/lib/components/Tooltip.svelte
- frontend/src/lib/components/apps/components/buttons/AppButton.svelte
- frontend/src/lib/components/apps/editor/AppEditorHeader.svelte
- frontend/src/lib/components/apps/editor/inlineScriptsPanel/InlineScriptEditor.svelte
Fixed low contrast on tooltip icons and removed placeholder padding of loader icon from the app button component.
> fix(frontend): App minor fixes

- frontend/src/lib/components/Popover.svelte
- frontend/src/lib/components/apps/components/form/AppForm.svelte
- frontend/src/lib/components/apps/components/helpers/RunnableComponent.svelte
- frontend/src/lib/components/apps/components/helpers/RunnableWrapper.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/InputsSpecsEditor.svelte
- form component
- fixed shifting 'Submit' button issue
- updated helper text
- general app builder
- added popover texts to some icon-only buttons
> fix(frontend): App form component

- frontend/src/lib/components/apps/components/dataDisplay/AppText.svelte
- frontend/src/lib/components/apps/components/helpers/InputValue.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/data.ts
- frontend/src/lib/components/apps/editor/settingsPanel/ComponentPanel.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/InputsSpecsEditor.svelte
- frontend/src/lib/components/apps/types.ts
- frontend/src/lib/utils.ts
Also added the option to append tooltips to component configuration fields
> feat(frontend): Add copy button option to app text display component

- frontend/src/lib/components/AppConnect.svelte
App connect instruction images were using relative path
> fix(frontend): Use absolute path on connect images

- frontend/src/lib/components/apps/components/form/AppForm.svelte
Fixes shifting of the submit button
> fix(frontend): App form component display

- frontend/src/lib/components/apps/editor/inlineScriptsPanel/InlineScriptsPanelList.svelte
- frontend/src/lib/components/apps/editor/inlineScriptsPanel/utils.ts
Moved the code to get the scripts of an app to a new file so it can be imported in the hub codebase
> fix(frontend): Prepare app scripts code for export

- frontend/src/lib/components/apps/editor/AppPreview.svelte
> feat(frontend): Add app preview lock

- backend/oauth_connect.json
Adding Square OAuth, as per the Contributor's Guide
> Square API OAuth

- frontend/src/lib/components/apps/components/helpers/RunnableComponent.svelte
- frontend/src/lib/components/apps/editor/AppEditor.svelte
- frontend/src/lib/components/apps/editor/AppEditorHeader.svelte
- frontend/src/lib/components/apps/editor/AppPreview.svelte
- frontend/src/lib/components/apps/editor/ComponentHeader.svelte
- frontend/src/lib/components/apps/types.ts
- Used a common store to communicate between components that are not in the same hierarchy
> feat(frontend): Open debug runs from component

- frontend/src/lib/components/apps/editor/ComponentEditor.svelte
- frontend/src/lib/components/apps/editor/GridEditor.svelte
- frontend/tailwind.config.cjs
> fix(frontend): Render popups above components in app editor

- backend/migrations/20221214105402_first_time_users.down.sql
- backend/migrations/20221214105402_first_time_users.up.sql
- backend/migrations/20230210145514_first_time_app.down.sql
- backend/migrations/20230210145514_first_time_app.up.sql
- backend/sqlx-data.json
- backend/windmill-api/src/users.rs
- backend/windmill-queue/src/jobs.rs
- frontend/src/lib/user.ts
- frontend/src/routes/(root)/(logged)/user/(user)/first-time/+page.js
- frontend/src/routes/(root)/(logged)/user/(user)/first-time/+page.svelte
- frontend/src/routes/(root)/(logged)/user/(user)/login/+page.svelte
- frontend/src/routes/scripts/p/[...path].svelte
- Tracking user first time status in DB & via cookie
- Asks user if they want to see the setup app (only admin@windmill.dev)
- Adds App to create new user & schedule to pull hub types
> Setup Experience

- frontend/src/lib/components/apps/components/AppDivider.svelte
- frontend/src/lib/components/apps/components/helpers/AlignWrapper.svelte
- frontend/src/lib/components/apps/editor/Component.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/componentStaticValues.ts
- frontend/src/lib/components/apps/editor/settingsPanel/AlignmentEditor.svelte
> feat(frontend): Add divider app component

- frontend/src/lib/components/apps/components/otherInputs/AppFileInput.svelte
- frontend/src/lib/components/apps/editor/Component.svelte
- frontend/src/lib/components/common/fileInput/FileInput.svelte
- frontend/src/lib/components/common/index.ts
File input with drag and drop. Files are returned as Base64 encoded strings.
**Known issues:**
- Large file errors are not really handled
> feat(frontend): Add file input app component

- frontend/src/lib/components/apps/editor/componentsPanel/ComponentList.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/ComponentPanel.svelte
- frontend/src/lib/components/apps/utils.ts
https://user-images.githubusercontent.com/456655/220953270-4480888c-f3b1-4770-94ad-10f4e200bbec.mov
> feat(frontend): Duplicate component

- frontend/README_DEV.md
1. Updated docker compose command
2. Added resolution steps for build issues on M1 Mac
3. Formatted file
> update build instructions

- frontend/src/lib/components/apps/editor/ComponentHeader.svelte
- frontend/src/lib/components/apps/editor/GridEditor.svelte
- frontend/src/lib/components/apps/editor/SubGridEditor.svelte
- frontend/src/lib/components/apps/editor/appUtils.ts
- frontend/src/lib/components/apps/editor/component/Component.svelte
- frontend/src/lib/components/apps/utils.ts
https://user-images.githubusercontent.com/456655/223778449-c81a9f63-5821-4ef4-a382-09aafca7b646.mov
> feat(frontend): add expand

- frontend/package-lock.json
- frontend/package.json
- frontend/src/lib/components/apps/editor/component/components.ts
- frontend/src/lib/components/apps/editor/settingsPanel/inputEditor/ColorInput.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/inputEditor/StaticInputEditor.svelte
- frontend/src/lib/components/apps/inputType.ts
> feat(frontend): Add color picker input to app

- frontend/src/lib/components/ScriptBuilder.svelte
- frontend/src/lib/components/SettingSection.svelte
> fix(frontend): Update setting accordion

- frontend/src/lib/components/apps/components/display/AppMap.svelte
> fix(frontend): fix map render

- frontend/src/lib/components/apps/editor/settingsPanel/InputsSpecEditor.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/InputsSpecsEditor.svelte
> fix(frontend): add missing optional chaining

- frontend/src/lib/components/Toggle.svelte
- frontend/src/lib/components/apps/components/helpers/HiddenComponent.svelte
- frontend/src/lib/components/apps/components/helpers/RunnableComponent.svelte
- frontend/src/lib/components/apps/components/helpers/RunnableWrapper.svelte
- frontend/src/lib/components/apps/editor/GridEditor.svelte
- frontend/src/lib/components/apps/editor/SettingsPanel.svelte
- frontend/src/lib/components/apps/editor/appUtils.ts
- frontend/src/lib/components/apps/editor/inlineScriptsPanel/InlineScriptsPanelList.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/SelectedRunnable.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/triggerLists/BackgroundScriptTriggerList.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/triggerLists/ComponentTriggerList.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/triggerLists/TriggerBadgesList.svelte
- frontend/src/lib/components/apps/inputType.ts
- frontend/src/lib/components/apps/types.ts
- frontend/src/lib/components/flows/flowStateUtils.ts
- Enable refresh when autoRefresh is disabled but the script has manual dependencies that changed
> fix(frontend): fix refresh with manual dependencies

- frontend/src/lib/components/apps/components/display/AppPdf.svelte
Fixes app PDF component header positioning in preview mode
> fix(frontend): PDF reader header positioning

- frontend/src/lib/components/apps/components/buttons/AppButton.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/ComponentList.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/ComponentPanel.svelte
- frontend/src/lib/components/common/button/Button.svelte
- fixed button "fill container" bug
- minor styling/typography updates here and there
> fix(frontend): Various app editor updates

- frontend/src/lib/components/CenteredModal.svelte
- frontend/src/lib/components/ScriptEditor.svelte
- frontend/src/lib/components/apps/editor/AppEditor.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/CssSettings.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/ComponentPanel.svelte
- frontend/src/lib/components/common/button/Button.svelte
- frontend/src/lib/components/common/tabs/Tab.svelte
- frontend/src/lib/components/flows/FlowEditor.svelte
- frontend/src/lib/components/flows/content/CapturePayload.svelte
- frontend/src/lib/components/icons/WindmillIcon.svelte
- frontend/src/routes/(root)/(logged)/+layout.svelte
- frontend/src/routes/(root)/(logged)/oauth/callback_slack/+page.svelte
- frontend/src/routes/(root)/(logged)/user/(user)/login/+page.svelte
- frontend/src/routes/(root)/(logged)/user/(user)/logout/+page.svelte
- frontend/src/routes/(root)/(logged)/user/(user)/workspaces/+page.svelte
- frontend/src/routes/(root)/(logged)/user/cli-success/+page.svelte
- frontend/src/routes/(root)/(logged)/workspace_settings/checkout/+page.svelte
- frontend/src/routes/scripts/p/[...path].svelte
- frontend/src/routes/user/login_callback/[client_name]/+page.svelte
- frontend/tailwind.config.cjs
- removed "Component" label from app settings tab
https://user-images.githubusercontent.com/43071496/230644875-bc52a4f0-3991-4206-b6b5-bbe93e30283f.mov
- fixed button container issues
- fixed component styling toggle button positioning
- fixed tab a11y warning
- Windmill logo now spins counter-clockwise - as the wind would spin it 🙂
> fix(frontend): Minor fixes

- frontend/src/lib/components/SavedInputs.svelte
- frontend/src/routes/(root)/(logged)/flows/run/[...path]/+page.svelte
- frontend/src/routes/(root)/(logged)/scripts/run/[...hash]/+page.svelte
https://user-images.githubusercontent.com/456655/231454455-13e5d723-f870-4496-b78d-b6ef97d1ed5c.mov
- Adding a toggle to open/close the SavedInput component
> feat(frontend): Add a toggle to open the saved inputs

- frontend/src/lib/components/apps/components/layout/AppTabs.svelte
Reverts windmill-labs/windmill#1409
> Revert "fix(frontend): Keep selected tab during renaming"

- frontend/src/lib/components/apps/editor/component/default-codes.ts
- frontend/src/lib/components/apps/editor/inlineScriptsPanel/EmptyInlineScript.svelte
- added Postgres defaults to charts and tables
- fixed existing ones
> fix(frontend): Update app default codes

- lsp/Dockerfile
Title says it all; see [Discord](https://discord.com/channels/930051556043276338/930051556043276341/1099240748408389664).
> LSP: Expose 3001 in the Docker image

- frontend/src/routes/(root)/(logged)/user/cli/+page.svelte
> fix(frontend): Update styling of CLI login request

- frontend/src/lib/components/apps/editor/inlineScriptsPanel/utils.ts
- frontend/src/lib/components/apps/utils.ts
https://user-images.githubusercontent.com/456655/233998859-02e7d631-5456-4335-b592-d16a0e332a62.mov
> feat(frontend): Support TS union type with a select field

- frontend/src/lib/components/CronInput.svelte
- frontend/src/lib/components/ScheduleEditor.svelte
- frontend/src/lib/components/SchemaEditor.svelte
- frontend/src/lib/components/apps/editor/AppEditorHeader.svelte
- frontend/src/lib/components/common/button/Button.svelte
- frontend/src/lib/components/common/button/ButtonDropdown.svelte
- frontend/src/lib/components/graph/svelvet/container/views/GraphView.svelte
- frontend/src/routes/(root)/(logged)/resources/+page.svelte
Small UI fixes:
- Align graph view buttons
- Fix Dropdown button z-index
> feat(frontend): Small style fix

- frontend/src/lib/components/apps/components/inputs/AppSliderInputs.svelte
https://github.com/windmill-labs/windmill/assets/456655/baa28559-6f20-42da-b2a2-aab0f7e753d4
> fix(frontend): add temp hidden span to compute the text max length

- backend/parsers/windmill-parser-py/src/lib.rs
adding pysmb to exceptions list
> Added an import exception for pysmb

- frontend/src/lib/components/apps/components/display/AppChartJs.svelte
- frontend/src/lib/components/apps/editor/AppPreview.svelte
- frontend/src/lib/components/apps/editor/component/Component.svelte
- frontend/src/lib/components/apps/editor/component/components.ts
- frontend/src/lib/components/apps/editor/component/sets.ts
- frontend/src/lib/components/apps/editor/componentsPanel/quickStyleProperties.ts
> feat(frontend): add plain chartjs component

- frontend/src/lib/components/apps/components/layout/AppTabs.svelte
- frontend/src/lib/components/apps/editor/component/Component.svelte
- frontend/src/lib/components/apps/editor/component/components.ts
- frontend/src/lib/components/apps/editor/settingsPanel/ComponentPanel.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/GridTab.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/GridTabDisabled.svelte
- frontend/src/lib/components/common/tabs/Tab.svelte
https://github.com/windmill-labs/windmill/assets/456655/d2fefbbe-a0f6-490f-98cc-8812eb993f83
> feat(frontend): disable tabs

- backend/migrations/20230522170237_schedule_on_failure.down.sql
- backend/migrations/20230522170237_schedule_on_failure.up.sql
- backend/sqlx-data.json
- backend/windmill-api/openapi.yaml
- backend/windmill-api/src/apps.rs
- backend/windmill-api/src/schedule.rs
- backend/windmill-common/src/jobs.rs
- backend/windmill-common/src/schedule.rs
- backend/windmill-queue/src/schedule.rs
- backend/windmill-worker/src/jobs.rs
- backend/windmill-worker/src/worker_flow.rs
- frontend/src/lib/components/Editor.svelte
- frontend/src/lib/components/ResourcePicker.svelte
- frontend/src/lib/components/ScheduleEditor.svelte
- frontend/src/lib/components/ScriptBuilder.svelte
- frontend/src/lib/script_helpers.ts
Introduce an error handler for handling failure of scheduled runs
> feat: schedule error handler

- init-db-as-superuser.sql
Reopened [this PR](https://github.com/windmill-labs/windmill/pull/1726)
> db_init: removed duplicate code

- frontend/src/lib/components/ArgInput.svelte
- frontend/src/lib/components/DisplayResult.svelte
- frontend/src/lib/components/Editor.svelte
- frontend/src/lib/components/FieldHeader.svelte
- frontend/src/lib/components/LogViewer.svelte
- frontend/src/lib/components/Required.svelte
- frontend/src/lib/components/ScriptEditor.svelte
- frontend/src/lib/components/common/tabs/Tab.svelte
- frontend/src/routes/(root)/(logged)/scripts/dev/+page.svelte
- frontend/src/routes/(root)/+layout.svelte
- frontend/tailwind.config.cjs
> feat(frontend): vscode extension dark mode

- frontend/src/lib/components/ScriptBuilder.svelte
- frontend/src/lib/components/apps/components/inputs/AppMultiSelect.svelte
> fix(frontend): Fix multi select custom css

- frontend/src/lib/components/details/DetailPageDetailPanel.svelte
- frontend/src/lib/components/details/DetailPageHeader.svelte
- frontend/src/lib/components/details/DetailPageLayout.svelte
- frontend/src/routes/(root)/(logged)/flows/get/[...path]/+page.svelte
- frontend/src/routes/(root)/(logged)/scripts/get/[...hash]/+page.svelte
> feat(frontend): add mobile view

- frontend/src/lib/components/apps/components/helpers/RunnableComponent.svelte
https://github.com/windmill-labs/windmill/issues/1843
> fix(frontend): App errors array

- frontend/src/lib/components/apps/components/helpers/RunnableComponent.svelte
- frontend/src/lib/components/apps/components/layout/AppDrawer.svelte
- frontend/src/lib/components/common/drawer/Drawer.svelte
- frontend/src/lib/components/common/drawer/DrawerContent.svelte
https://github.com/windmill-labs/windmill/assets/456655/5c8a4088-964a-49a8-91ff-3bbfc4133831
Fix drawer height issue
> fix(frontend): Fix app drawer display + add missing flatten

- frontend/src/lib/components/apps/components/inputs/AppMultiSelect.svelte
- frontend/src/lib/components/apps/svelte-select/lib/Select.svelte
- frontend/src/lib/utils.ts
> fix(frontend): only forward css variables

- backend/windmill-common/src/scripts.rs
related to
* https://github.com/launchbadge/sqlx/pull/2617#issuecomment-1636808249
* https://github.com/launchbadge/sqlx/pull/2617#issuecomment-1637005378
> refactor(backend): alternative approach for sqlx ^0.7 upgrade

- backend/windmill-common/src/scripts.rs
Reverts windmill-labs/windmill#1884
> Revert "refactor(backend): alternative approach for sqlx ^0.7 upgrade"

- frontend/src/lib/components/details/WebhooksPanel.svelte
It's probably not paylod, it's probably missing an `a`
> fix: s/paylod/payload

- frontend/src/lib/components/SchemaEditor.svelte
- frontend/src/lib/components/SchemaModal.svelte
Fixes #1936 
Changed modal title as well for additional context.
> Fix schema property overwrite on edit

- frontend/src/lib/components/apps/components/inputs/AppDateInput.svelte
- frontend/src/lib/components/apps/editor/component/components.ts
> feat(frontend): Add an output format

- frontend/src/lib/components/DBSchemaExplorer.svelte
- frontend/src/lib/components/Editor.svelte
- frontend/src/lib/components/ResourcePicker.svelte
- frontend/src/lib/components/TestConnection.svelte
- frontend/src/lib/components/codeGen/lib.ts
including autocomplete and AI gen
> feat(frontend): schema explorer, autocomplete and db aware AI for mysql

- frontend/src/lib/components/common/button/Button.svelte
- frontend/src/lib/components/common/button/ButtonDropdown.svelte
- frontend/src/routes/kitchen_sink/+page.svelte
> fix(frontend): Fix dropdown buttons

- frontend/src/lib/components/codeGen/ScriptGen.svelte
- frontend/src/routes/(root)/(logged)/workspace_settings/+page.svelte
> feat: unveil windmill AI

- frontend/src/lib/components/apps/components/icon.ts
https://github.com/windmill-labs/windmill/issues/1919
> fix(frontend): Fix app icons

- frontend/src/lib/components/apps/components/inputs/AppFileInput.svelte
- frontend/src/lib/components/apps/editor/component/components.ts
> feat(frontend): Add config to optionally include mimetype

- frontend/src/lib/components/DBSchemaExplorer.svelte
- frontend/src/lib/components/TestConnection.svelte
- frontend/src/lib/infer.ts
- frontend/src/lib/utils.ts
- add test connection for bigquery
- test connection at interval before timing out
- use specific resource type for bigquery
> feat: add test connection for bigquery

- backend/oauth_connect.json
- backend/windmill-api/src/db.rs
Oauth Config to call Google Workspace APIs. 
https://developers.google.com/admin-sdk/directory/v1/guides/authorizing
> Add google workspace oauth connection config

- frontend/src/lib/components/RunChart.svelte
- frontend/src/routes/(root)/(logged)/runs/[...path]/+page.svelte
Fix an issue where the chart would make the page freeze because of the lack of a relative container.
https://www.chartjs.org/docs/latest/configuration/responsive.html#important-note
> fix(frontend): Fix lagging issues when resizing

- frontend/src/lib/components/apps/components/display/table/AppTable.svelte
- frontend/src/lib/components/apps/components/display/table/AppTableFooter.svelte
- frontend/src/lib/components/apps/components/layout/AppList.svelte
- frontend/src/lib/components/apps/editor/component/components.ts
- frontend/src/lib/components/apps/editor/component/default-codes.ts
- frontend/src/lib/components/apps/editor/inlineScriptsPanel/InlineScriptEditor.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/OneOfInputSpecsEditor.svelte
https://github.com/windmill-labs/windmill/assets/456655/bc999dc4-e970-4c1e-85c0-090902dc55f8
> feat(frontend): Add List pagination + add loading state in tables

- frontend/src/lib/components/apps/components/display/table/AppTable.svelte
I was not able to find any downside with this approach. 
Will add a PR to the docs repo also where this change will be used.
> Tanstack init config for width will now be applied to columns

- frontend/src/lib/components/CronInput.svelte
- frontend/src/lib/components/apps/components/inputs/AppMultiSelect.svelte
> fix(frontend): Fix app multiselect dark mode

- backend/parsers/windmill-parser-py-imports/src/lib.rs
https://pypi.org/project/mail-parser/
https://pypi.org/project/mail-parser-reply/
> py imports replacement mailparser and mailparser_reply

- frontend/src/lib/components/home/ItemsList.svelte
- frontend/src/lib/navigation.ts
- frontend/src/routes/(root)/(logged)/+page.svelte
https://github.com/windmill-labs/windmill/assets/456655/fb9a9df3-270a-4656-8000-bb871fbdfabd
@hcourdent
> fix(frontend): Fix hub navigation

- backend/windmill-worker/src/pg_executor.rs
Looked into the code and it was an easy fix, similar to what you have been done to convert the other postgres types
> fix #2257 TIME  convertion in pg_executor.rs

- frontend/src/lib/components/apps/editor/componentsPanel/ThemeList.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/ThemeRow.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/ComponentControl.svelte
- frontend/src/lib/components/table/Cell.svelte
- frontend/src/lib/components/table/DataTable.svelte
> fix(frontend): fix theme UI

- backend/migrations/20230927215813_add_app_groups.down.sql
- backend/migrations/20230927215813_add_app_groups.up.sql
- backend/windmill-api/src/workspaces.rs
- frontend/src/lib/components/apps/editor/appUtils.ts
- frontend/src/lib/components/apps/editor/component/ComponentNavigation.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/ComponentList.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/GroupList.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/GroupManagementDrawer.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/GroupNameEditor.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/GroupRow.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/groupUtils.ts
- frontend/src/lib/components/apps/editor/settingsPanel/ComponentPanel.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/GridGroup.svelte
https://github.com/windmill-labs/windmill/assets/456655/a46f6862-f36c-441e-9ccd-9b0d3e01d5f6
> feat(frontend): add app groups management

- frontend/package-lock.json
- frontend/package.json
- frontend/src/lib/components/SavedInputs.svelte
- frontend/src/lib/components/apps/components/inputs/AppRangeInput.svelte
- frontend/src/lib/components/flows/content/FlowInput.svelte
https://github.com/windmill-labs/windmill/assets/456655/ff489edd-a03b-47f3-b76b-b696d3a8d09a
- Updated the Range library
- Fix disabled
> feat(frontend): copy schema from json and past runs in flow inputs

- README.md
- backend/.sqlx/query-025e5bf6aef56e9832239489daf21b4970d84529cf7ed7928ce2dcfec8b007f0.json
- backend/migrations/20231002123723_notify_delete_config.down.sql
- backend/migrations/20231002123723_notify_delete_config.up.sql
- backend/src/main.rs
- backend/src/monitor.rs
- backend/windmill-api/src/settings.rs
- backend/windmill-common/src/global_settings.rs
- backend/windmill-worker/src/bun_executor.rs
- backend/windmill-worker/src/deno_executor.rs
- backend/windmill-worker/src/python_executor.rs
- backend/windmill-worker/src/worker.rs
- frontend/src/lib/components/InstanceSettings.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/CssSettings.svelte
- frontend/src/lib/components/instanceSettings.ts
> feat: add npm_config_registry support for bun, deno and being settable from UI

- backend/Cargo.lock
- backend/parsers/windmill-parser-sql/src/lib.rs
- backend/parsers/windmill-parser-wasm/pkg/package.json
- backend/parsers/windmill-parser-wasm/pkg/windmill_parser_wasm.js
- backend/windmill-worker/Cargo.toml
- backend/windmill-worker/src/pg_executor.rs
- frontend/package-lock.json
- frontend/package.json
should fix #2134 and #2237 
!parser not yet published on npm!
> fix: add numeric, array and date types

- Dockerfile
I have tested this on CE version and make sure it can build (but not test for running) on EE version.
> Upgrade debian version to bookworm

- backend/Cargo.lock
- backend/windmill-api-client/Cargo.toml
Reverts windmill-labs/windmill#2236
> Revert "chore(deps): bump openapiv3 from 1.0.2 to 1.0.3 in /backend"

- backend/Cargo.lock
- backend/windmill-api-client/Cargo.toml
Reverts windmill-labs/windmill#2256
> Revert "chore(deps): bump prettyplease from 0.1.25 to 0.2.15 in /backend"

- frontend/src/lib/components/InstanceSettings.svelte
- frontend/src/lib/components/SuperadminSettings.svelte
- frontend/src/lib/components/instanceSettings.ts
> fix(frontend): add a validation for base url

- backend/windmill-common/src/lib.rs
closes https://github.com/windmill-labs/windmill/issues/2473
I did it how I thought you might want it.
This leaves a migration path, but still favors the more secure option.
let me know if anything.
> feat: enable secret to be read from file

- backend/parsers/windmill-parser-py-imports/src/lib.rs
- backend/parsers/windmill-parser-py/src/lib.rs
- backend/tests/worker.rs
- backend/windmill-common/src/worker.rs
- backend/windmill-queue/src/jobs.rs
- frontend/src/lib/components/WorkspaceGroup.svelte
https://github.com/windmill-labs/windmill/assets/18011812/94e17796-1098-442a-a1f5-c82023062258
> feat: Priority worker tags

- frontend/src/lib/components/apps/components/inputs/AppTextInput.svelte
- frontend/src/lib/components/apps/editor/component/components.ts
https://github.com/windmill-labs/windmill/issues/2511
> fix(frontend): add a disabled prop to text inputs

- frontend/src/routes/(root)/(logged)/schedules/+page.svelte
> fix: Load schedule statistics in background

- frontend/src/lib/components/common/table/AppRow.svelte
- frontend/src/lib/components/common/table/FlowRow.svelte
- frontend/src/lib/components/common/table/RawAppRow.svelte
- frontend/src/lib/components/common/table/Row.svelte
- frontend/src/lib/components/common/table/ScriptRow.svelte
- frontend/src/lib/components/home/Item.svelte
- frontend/src/lib/components/home/ItemsList.svelte
- frontend/src/lib/components/home/TreeView.svelte
- frontend/src/lib/components/home/treeViewUtils.ts
https://github.com/windmill-labs/windmill/assets/456655/f018ab9a-a871-4259-8464-5273fc4813dc
> feat(frontend): add treeview

- frontend/src/lib/components/common/table/Row.svelte
> feat(frontend): update displayed path for treeview

- frontend/src/lib/components/apps/components/display/table/AppAggridTable.svelte
- frontend/src/lib/components/apps/components/display/table/AppAggridTableEe.svelte
- frontend/src/lib/components/apps/editor/component/Component.svelte
- frontend/src/lib/components/apps/editor/component/components.ts
- frontend/src/lib/components/apps/editor/componentsPanel/CssHelperPanel.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/cssUtils.ts
- frontend/src/lib/components/sidebar/UserMenu.svelte
- frontend/src/lib/components/table/Cell.svelte
https://github.com/windmill-labs/windmill/assets/456655/70502750-cbb3-4e2d-ad70-acd0a8f7db4c
> feat(frontend): Ag grid styling

- frontend/src/lib/components/apps/components/layout/AppTabs.svelte
> fix(frontend): add missing classes when tabs are in sidebar mode

- backend/.sqlx/query-11ae5e1aade2bc9a78af2d956ece73766ae3330319619a68383b508a76f2d19c.json
- backend/.sqlx/query-254776959f60455a00a2c29a1783ee6b27c836197df6454d3bb5c59441c34f44.json
- backend/.sqlx/query-52ad1773a9f5a1b6be1bb16af408f051f27d3f21b615c468b85aa75b64d943db.json
- backend/.sqlx/query-539d9ae486c7d1f5fb8c7278d698675b04359182b781b0cb0164402b798a7fef.json
- backend/.sqlx/query-542ebd3d6cd8522d117112ef9eb13ff95b93d67994823a4a84d37639eb17e0b9.json
- backend/.sqlx/query-620ddf29c5e867079df4c2aa6e80bccb19beeb9ddfa308ca97f254cd5ba8157e.json
- backend/.sqlx/query-9d3556319411a27a875bf6cf0e5eda837cc63e4d8be912c0b5bfeea4a0c8db2e.json
- backend/.sqlx/query-a9915d3c72a278ff08fbe6571c2a4fc993507e255004107345b7151322e063de.json
- backend/.sqlx/query-b6074eb9369de071f79165bf506fbc44f1688035e1928b4c3649d875187b1e1d.json
- backend/.sqlx/query-c7febee7146a28481ce36f3570bceb38751a6527827525a582d9f8804981f552.json
- backend/.sqlx/query-d48070ef889723f408ed6c1a97b5ab9f0e98340cd33c6e29824f6030f0089071.json
- backend/windmill-api/openapi-deref.yaml
- backend/windmill-api/openapi.yaml
- backend/windmill-api/src/schedule.rs
- backend/windmill-api/src/settings.rs
- backend/windmill-api/src/workspaces.rs
- frontend/src/lib/components/ScheduleEditorInner.svelte
> feat: Add override all schedule handlers button

- frontend/src/lib/components/apps/components/display/table/AppCell.svelte
- frontend/src/lib/components/wizards/TableColumnWizard.svelte
> feat(frontend): add a way to customise the link's label

- backend/windmill-worker/src/pg_executor.rs
- frontend/src/lib/components/AppConnect.svelte
- feat: cache pg connection
- fix wmill dev
> feat: cache postgres connection

- frontend/src/lib/components/FlowBuilder.svelte
- frontend/src/lib/components/FlowGraphViewerStep.svelte
- frontend/src/routes/(root)/(logged)/flows/get/[...path]/+page.svelte
- frontend/tailwind.config.cjs
https://github.com/windmill-labs/windmill/assets/456655/a1051873-7318-40c0-a137-009b9b006c07
> fix(frontend): Fix Step viewer

- backend/tests/worker.rs
- backend/windmill-worker/src/go_executor.rs
Caused by https://github.com/windmill-labs/windmill/commit/b13cc58315ea07d67d98bffb907e2cbd0c1d6b7d#diff-9f2b0f927e0a13c103a4e641c255cc58e4f745cc4cafafb28a7296e8c7f9a1ba I believe
> fix: main broken tests

- backend/windmill-api/openapi-deref.yaml
- backend/windmill-api/openapi.yaml
- backend/windmill-api/src/job_helpers.rs
- frontend/src/lib/components/ArgInfo.svelte
- frontend/src/lib/components/ArgInput.svelte
- frontend/src/lib/components/DisplayResult.svelte
- frontend/src/lib/components/S3FilePicker.svelte
- frontend/src/lib/components/propertyPicker/ObjectViewer.svelte
feat: Expanding an s3object result now opens the S3 file browser
chore: adding pagination for file list
> feat: Expanding an s3object result now opens the S3 file browser

- frontend/src/lib/components/RunForm.svelte
https://github.com/windmill-labs/windmill/assets/456655/d4daba81-28c1-4c04-9999-8789e60ae930
> fix(frontend): use popover for schedule for later on the runs page

- frontend/src/lib/components/apps/editor/AppEditorTutorial.svelte
- frontend/src/lib/components/tutorials/SkipTutorials.svelte
- frontend/src/lib/components/tutorials/Tutorial.svelte
- frontend/src/lib/components/tutorials/TutorialControls.svelte
- Used the Button component with icons
- Added help box in the first step
> fix(frontend): improve tutorial ux

- python-client/wmill/README.md
- python-client/wmill/wmill/client.py
This PR adds the `cancel_running` and `run_script` methods to the `wmill` client global scope and fleshes out the `README.md` to highlight the more advanced usage patterns available with the `Windmill` class
> Feat(python): Quality of Life improvements to Python client

- python-client/README.md
- python-client/wmill/wmill/client.py
Modified the 'get_resource' function in 'wmill/client.py' to additionally return a 'dict', providing support for dictionaries in addition to strings and None.
Also update the top-level python readme with recently added functionality
> feat(python): Update return type for 'get_resource' function

- backend/windmill-worker/src/deno_executor.rs
- frontend/src/lib/components/DisplayResult.svelte
- frontend/src/lib/components/propertyPicker/ObjectViewer.svelte
Also pimping a little bit the s3 explorer button now that we can have more than one in the same result preview:
> fix: Allow run git for Deno

- frontend/src/lib/components/Editor.svelte
> fix: db schema autocomplete

- frontend/src/routes/(root)/(logged)/workspace_settings/+page.svelte
> chore: Updating git sync info

- frontend/src/lib/components/ErrorOrRecoveryHandler.svelte
- frontend/src/routes/(root)/(logged)/workspace_settings/+page.svelte
> feat: Add a git sync test button

- backend/windmill-common/src/worker.rs
- backend/windmill-worker/src/bun_executor.rs
- backend/windmill-worker/src/common.rs
- backend/windmill-worker/src/deno_executor.rs
- backend/windmill-worker/src/python_executor.rs
- backend/windmill-worker/src/worker.rs
- frontend/src/lib/components/WorkspaceGroup.svelte
https://github.com/windmill-labs/windmill/assets/18011812/c087eb49-b60c-4eda-9901-b29b4aac3ba7
> feat: EnvVar allow list is configurable from the UI

- backend/windmill-api/openapi-deref.yaml
- backend/windmill-api/src/flows.rs
- backend/windmill-common/src/flows.rs
- frontend/src/lib/components/flows/content/FlowRetries.svelte
- openflow.openapi.yaml
https://github.com/windmill-labs/windmill/assets/18011812/324f97b5-eb9b-4a87-9d64-ec9e58238ac5
> feat: Add jitter to exponential backoff

- frontend/src/lib/components/WorkspaceGroup.svelte
https://github.com/windmill-labs/windmill/assets/18011812/cae86ae2-1666-4553-9f67-a46880c7aa80
> fix: Simplify worker env var input

- backend/.sqlx/query-da4525f02e83bdd0e2d9eb9c6a9b29a6bff4a32f3a4ac5581a0ce6eb465c97e9.json
- backend/.sqlx/query-f179cefbceadc8c3dc6442c74dd1d9d57bee47919592d8c75cdeb38ba1c971cb.json
- backend/windmill-api/openapi-deref.yaml
- backend/windmill-api/openapi.yaml
- backend/windmill-api/src/jobs.rs
- backend/windmill-queue/src/jobs.rs
- docker-compose.yml
- frontend/src/lib/components/PersistentScriptDrawer.svelte
- frontend/src/lib/components/flows/content/FlowModuleComponent.svelte
- frontend/src/routes/(root)/(logged)/run/[...run]/+page.svelte
- frontend/src/routes/(root)/(logged)/scripts/get/[...hash]/+page.svelte
https://github.com/windmill-labs/windmill/assets/18011812/5d9a8731-719a-4f0d-8b25-462e4199a4d5
> feat: Cancel persistent script runs from drawer

- backend/windmill-api/openapi-deref.yaml
- backend/windmill-api/openapi.yaml
- backend/windmill-api/src/job_helpers.rs
- frontend/src/lib/components/S3FilePicker.svelte
- python-client/tests/wmill_client_test.py
- python-client/wmill/wmill/client.py
- typescript-client/client.ts
> feat: Download file button in S3 file explorer

- frontend/src/lib/components/InstanceSettings.svelte
- frontend/src/lib/components/ZitadelSetting.svelte
This PR adds possibility to integrate Windmill with Zitadel IDP via OIDC
> feat: Add Zitadel IDP

- backend/windmill-worker/src/python_executor.rs
You can now do:
```python
#extra_requirements:
#git+https://github.com/windmill-labs/windmill.git#subdirectory=python-client/wmill/
import wmill
def main():
...
return {}
```
> fix: Python imports from git repository

- frontend/src/routes/(root)/(logged)/apps/edit/[...path]/+page.svelte
https://github.com/windmill-labs/windmill/issues/2903
> fix(frontend): fix save draft when the app has no versions

- backend/windmill-api/openapi-deref.yaml
- backend/windmill-api/openapi.yaml
- backend/windmill-api/src/job_helpers.rs
- frontend/src/lib/components/S3FilePicker.svelte
- frontend/src/lib/components/common/fileUpload/FileUploadModal.svelte
https://github.com/windmill-labs/windmill/assets/18011812/b2388927-127b-44ef-b651-8f0949dc2013
> feat: S3 delete file and upload new

- frontend/src/lib/components/apps/editor/settingsPanel/DecisionTreeGraphEditor.svelte
> fix(frontend): fix wording

- frontend/src/routes/(root)/(logged)/flows/get/[...path]/+page.svelte
- frontend/src/routes/(root)/(logged)/scripts/get/[...hash]/+page.svelte
> feat(frontend): add the view runs buttons for operators

- backend/windmill-api/openapi-deref.yaml
- backend/windmill-api/openapi.yaml
- backend/windmill-api/src/groups.rs
- frontend/src/lib/components/InstanceGroupEditor.svelte
- frontend/src/routes/(root)/(logged)/instance_groups/+page.js
- frontend/src/routes/(root)/(logged)/instance_groups/+page.svelte
https://github.com/windmill-labs/windmill/assets/18011812/670a1f4c-34dd-4aa3-a5e2-919f925869ba
> feat: Instance group management page

- backend/Cargo.lock
- backend/migrations/20240112131322_git_sync_multi.down.sql
- backend/migrations/20240112131322_git_sync_multi.up.sql
- backend/windmill-api/openapi-deref.yaml
- backend/windmill-api/openapi.yaml
- backend/windmill-api/src/workspaces.rs
- backend/windmill-git-sync/Cargo.toml
- backend/windmill-git-sync/src/lib.rs
- frontend/src/routes/(root)/(logged)/workspace_settings/+page.svelte
https://github.com/windmill-labs/windmill/assets/18011812/776efb34-4de5-4405-860e-dd28dde5a039
> feat: Git sync to multiple repo

- frontend/src/lib/components/apps/components/display/charts/AppAgCharts.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/ArrayStaticInputEditor.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/ComponentPanelDataSource.svelte
- frontend/src/lib/components/wizards/AgChartWizard.svelte
> feat(frontend): add support for range area

- frontend/src/lib/components/ArgInput.svelte
- frontend/src/lib/components/S3ObjectPicker.svelte
- frontend/src/lib/components/common/fileInput/FileInput.svelte
- frontend/src/lib/components/common/fileUpload/FileUpload.svelte
> feat(frontend): handle file default value

- backend/windmill-api/src/jobs.rs
- backend/windmill-common/src/flow_status.rs
- backend/windmill-common/src/flows.rs
- backend/windmill-worker/src/worker_flow.rs
- frontend/src/lib/components/flows/content/FlowModuleSuspend.svelte
- frontend/src/routes/approve/[workspace]/[job]/[resume]/[hmac]/+page.svelte
- openflow.openapi.yaml
> feat: disable self approval toggle

- cli/script.ts
> Remove ansi codes in script run silent mode

- frontend/src/lib/components/common/tabs/Tab.svelte
- frontend/src/lib/components/flows/content/FlowModuleComponent.svelte
- frontend/src/lib/components/flows/content/FlowSettings.svelte
- frontend/src/lib/components/home/ItemsList.svelte
> feat(frontend): add status when a flow setting is enabled

- frontend/src/lib/components/runs/RunRow.svelte
> fix(frontend): Truncate path on the run page

- docker-compose.yml
> fix(typo): typo error on docker-compose.yml

- backend/windmill-common/src/lib.rs
- backend/windmill-worker/src/common.rs
- backend/windmill-worker/src/worker.rs
Current rust code in `windmill-backend` couldn't be built on Windows OS, beacause of lack of some checks.
I modify code slightly to fix build on Windows
I have read the CLA Document and I hereby sign the CLA
> Fix build for Windows

- frontend/src/lib/components/copilot/IteratorGen.svelte
- frontend/src/lib/components/copilot/MetadataGen.svelte
- frontend/src/lib/components/copilot/PredicateGen.svelte
- frontend/src/lib/components/copilot/StepInputGen.svelte
- frontend/src/lib/components/copilot/StepInputsGen.svelte
- **fix: AI fill deep copy before slicing modules**
- **feat: green to accept + improve single input gen prompt**
> fix: ai fill deep copy before slicing modules + minor improvements

- frontend/src/lib/components/apps/editor/AppEditor.svelte
- frontend/src/lib/components/apps/editor/AppEditorHeader.svelte
- frontend/src/lib/components/apps/editor/componentsPanel/ComponentList.svelte
- frontend/src/lib/components/apps/editor/contextPanel/ContextPanel.svelte
- frontend/src/lib/components/apps/editor/contextPanel/DebugPanel.svelte
> feat(frontend): App debug mode

- frontend/src/lib/components/Path.svelte
> Subfolder indicator

- backend/.sqlx/query-0a686ca61444d7ad7484071727aa039a6ea6697e5a49a633b767c052aa3e0a18.json
- backend/.sqlx/query-254776959f60455a00a2c29a1783ee6b27c836197df6454d3bb5c59441c34f44.json
- backend/.sqlx/query-260feb784bb0b223bd9276d6a82bd26be90efb17a4323b9673e93ff88513942a.json
- backend/.sqlx/query-2f42460fdd8aa125c8fd46b3cd02e47f57de0f073d3ce3bc7d21a7e404a83b5c.json
- backend/.sqlx/query-2fa6e9c2cfc4f4ddbaa91793686feb9773b36993dd417019db51fa59fd4952c3.json
- backend/.sqlx/query-3dd6ba886b214274d9453667e3732421251c3a0d84b0909206447a3927bad8b3.json
- backend/.sqlx/query-60b3a59805d463a61eed68072d1ea032b00fc9bd7a6db22f530f67eb9730fa3b.json
- backend/.sqlx/query-620ddf29c5e867079df4c2aa6e80bccb19beeb9ddfa308ca97f254cd5ba8157e.json
- backend/.sqlx/query-661f472ff3860983322162420457f5033b9c9afc344d9c3e385ba20a3ad2197a.json
- backend/.sqlx/query-6b313cc9a57ae3c943bda4a3213f7f6231a44b6ef5a52754074d136007f4f72a.json
- backend/.sqlx/query-9d3556319411a27a875bf6cf0e5eda837cc63e4d8be912c0b5bfeea4a0c8db2e.json
- backend/.sqlx/query-b69891c25dd029b1a54e97ace292433e1485324ff7dc802fe75d21c8c6db1d42.json
- backend/.sqlx/query-ca5f42cb0e368d0817461600152aabefe718829fb6eae2f681c4c8328acc94b2.json
- backend/.sqlx/query-ef132ac8d79579b08d7359789b6f22991f51e1c945efc2924df6253d62b83bba.json
- backend/.sqlx/query-f96dd1dd944506c07ad58d178e9b6a09259fedca329d790c34e58703bf26f34c.json
- backend/windmill-api/openapi.yaml
- backend/windmill-api/src/users.rs
- backend/windmill-api/src/workspaces.rs
- cli/conf.ts
- cli/deps.ts
- cli/pull.ts
- cli/sync.ts
- cli/types.ts
- cli/user.ts
- **feat: wmil sync for users and groups**
- **fix: sort admins**
- **fix: sqlx build**
TODO:
- update deno client and set latest in deps.ts
> feat: sync users and groups

- Dockerfile
1. define mod when COPY
2. WORKDIR will create path if not exsit
> Reduce two layers

- frontend/src/lib/components/LogViewer.svelte
Not trying to be petty, just happened to see this during some of my testing.
> Fixing typo in LogViewer.svelte

- frontend/src/lib/components/apps/components/layout/AppDecisionTree.svelte
- frontend/src/lib/components/apps/editor/settingsPanel/DecisionTreeGraphEditor.svelte
Fix for:
https://github.com/windmill-labs/windmill/issues/3354
https://github.com/windmill-labs/windmill/issues/3353
> fix(frontend): Disabled delete node + correctly update debug menu when nodes are deleted

- frontend/src/lib/components/table/AutoDataTable.svelte
https://github.com/windmill-labs/windmill/assets/456655/bcb92834-be19-4e7f-9eb3-feee9889082f
> fix(frontend): correctly change the currentPage when perPage changes

- frontend/src/lib/components/JobArgs.svelte
This is a great feature to have to be able to copy and paste the real values. The if statement was not actually triggering locally though, so I fixed it.
> [FIX] Generated python local code tester had wrong if statement syntax

- .github/workflows/benchmark.yml
- benchmarks/benchmark_suite.ts
- benchmarks/suite_config.json
- benchmarks/suite_dedicated.json
- **fix: benchmarks action only push once**
- **fix: benchmark artifacts**
- **fix: include past data**
- **fix: don't save dedicated warmup**
- **fix: fetch existing data directly from gh**
> fix: benchmark action single push

- frontend/src/lib/components/apps/editor/settingsPanel/GridPane.svelte
Fix: https://github.com/windmill-labs/windmill/issues/3367
> fix(frontend): Fix the pane delete button

- frontend/src/lib/components/apps/components/inputs/AppFileInput.svelte
- frontend/src/lib/components/common/fileInput/FileInput.svelte
https://github.com/windmill-labs/windmill/issues/3481
https://github.com/windmill-labs/windmill/assets/456655/cb82cf25-8bda-4148-960f-e414dd0e1fb3
> feat(frontend): Add support for clearFiles in the file input component

- frontend/src/lib/components/apps/editor/component/components.ts
- **fix: date-fns tooltip**
- **fix: date-fns docs version**
> fix: date-fns tooltip format info

- .github/workflows/docker-image.yml
- Dockerfile
Reverts windmill-labs/windmill#3505
> Revert "remove libprotobuf"

- frontend/src/lib/components/home/Item.svelte
> fix(frontend): Fix bypass confirmation shortcut

- frontend/src/lib/assets/app.css
- frontend/src/lib/components/apps/components/display/AppMap.svelte
- frontend/src/lib/components/apps/editor/component/components.ts
https://github.com/windmill-labs/windmill/assets/456655/38f6eedd-3fa2-4497-8f02-e4fe5bbd4b3e
> feat(frontend): add map lock + properly display marker title

- README.md
Added some instructions to setup a local environment based on ones i found from a past commit. I managed to succesfully compile and run a local setup.
> Add dev environment setup instructions

- .github/change-versions.sh
- .github/workflows/jsr_on_release.yml
Based on this template: https://jsr.io/docs/publishing-packages#publishing-from-github-actions
Only thing left should be to add the token to secrets
> Add actions to publish to JSR

- frontend/src/lib/components/apps/components/display/AppDisplayComponent.svelte
- frontend/src/lib/components/apps/components/display/AppJobIdFlowStatus.svelte
- frontend/src/lib/components/apps/components/display/AppJobIdLogComponent.svelte
> fix(frontend): improve result, flow status and log components

- frontend/src/lib/components/FlowGraphViewer.svelte
- frontend/src/lib/components/FlowGraphViewerStep.svelte
Fix: https://github.com/windmill-labs/windmill/issues/3648
https://github.com/windmill-labs/windmill/assets/456655/53221fb7-3a29-4655-9f2c-0d0cf31f9075
> fix(frontend): Fix subflow viewer

- backend/.sqlx/query-bbd5f968d7b62a55a7ebf7b98cfd411678ce544fdb9472d8d223235fb2818aaf.json
- backend/windmill-api/openapi.yaml
- backend/windmill-api/src/inputs.rs
- frontend/src/lib/components/SavedInputs.svelte
> fix: load large args of previous runs dynamically

- frontend/src/lib/components/FlowGraphViewerStep.svelte
Added a button to copy the path of a subflow to address: https://github.com/windmill-labs/windmill/issues/3681
> feat(frontend): Add a button tocopy the path of a subflow

- frontend/src/lib/components/SavedInputs.svelte
- frontend/src/lib/utils.ts
Fix for: https://github.com/windmill-labs/windmill/issues/3680
> feat(frontend): add missing date in the previous run panel

- backend/migrations/20240515115413_add_underscore_to_proper_email_constraints.down.sql
- backend/migrations/20240515115413_add_underscore_to_proper_email_constraints.up.sql
Reverts windmill-labs/windmill#3739
> Revert "fix(backend): remove email constraints from DB"

- backend/Cargo.lock
- backend/parsers/windmill-parser-bash/src/lib.rs
- backend/parsers/windmill-parser-go/src/lib.rs
- backend/parsers/windmill-parser-graphql/src/lib.rs
- backend/parsers/windmill-parser-php/src/lib.rs
- backend/parsers/windmill-parser-py/src/lib.rs
- backend/parsers/windmill-parser-sql/src/lib.rs
- backend/parsers/windmill-parser-ts/src/lib.rs
- backend/parsers/windmill-parser-wasm/pkg/package.json
- backend/parsers/windmill-parser-wasm/pkg/windmill_parser_wasm.js
- backend/parsers/windmill-parser-wasm/tests/wasm.rs
- backend/parsers/windmill-parser/Cargo.toml
- backend/parsers/windmill-parser/src/lib.rs
- backend/parsers/windmill-sql-datatype-parser-wasm/Cargo.toml
- backend/windmill-worker/src/bigquery_executor.rs
- backend/windmill-worker/src/mysql_executor.rs
- backend/windmill-worker/src/pg_executor.rs
- backend/windmill-worker/src/snowflake_executor.rs
- frontend/package-lock.json
- frontend/package.json
- frontend/src/lib/script_helpers.ts
Reverts windmill-labs/windmill#4104
> Revert "feat: multi statement sql"

- frontend/package-lock.json
- frontend/package.json
Reverts windmill-labs/windmill#4832
> Revert "chore(deps-dev): bump @sveltejs/kit from 2.5.0 to 2.9.0 in /frontend"

- frontend/src/lib/components/copilot/chat/core.ts
- frontend/src/lib/components/copilot/lib.ts
Fixes https://github.com/windmill-labs/windmill/issues/5688
> fix: Ai Chat: do not send tools if empty + respond even if tool fails
